appium/appium-espresso-driver

- research.md
It is possible to launch activities other than those in the app the tests are associated with.
> Add info about launching other activities

- espresso-server/app/src/androidTest/java/io/appium/espressoserver/lib/Handlers/CreateSession.java
- espresso-server/app/src/androidTest/java/io/appium/espressoserver/lib/Handlers/Status.java
- espresso-server/app/src/androidTest/java/io/appium/espressoserver/lib/Http/Response/AppiumResponse.java
- espresso-server/app/src/androidTest/java/io/appium/espressoserver/lib/Http/Server.java
- espresso-server/app/src/androidTest/java/io/appium/espressoserver/lib/Model/Appium.java
- espresso-server/app/src/androidTest/java/io/appium/espressoserver/lib/Model/AppiumStatus.java
- espresso-server/app/src/androidTest/java/io/appium/espressoserver/lib/Model/GsonAdapters/AppiumStatusAdapter.java
* Added AppiumStatus enum type that maps to an int
* Had to add a Gson adapter that converts it to int because Gson doesn’t automatically convert enums to int types
> Changed appium status from `int` to `enum`

- espresso-server/app/src/androidTest/java/io/appium/espressoserver/lib/Handlers/Finder.java
- espresso-server/app/src/androidTest/java/io/appium/espressoserver/lib/Http/Response/AppiumResponse.java
- espresso-server/app/src/androidTest/java/io/appium/espressoserver/lib/Http/Response/BaseResponse.java
- espresso-server/app/src/androidTest/java/io/appium/espressoserver/lib/Http/Router.java
- espresso-server/app/src/androidTest/java/io/appium/espressoserver/lib/Http/Server.java
- espresso-server/app/src/androidTest/java/io/appium/espressoserver/lib/Model/Error.java
* Appium has `status`, `sessionId`, `id` and `value` as it’s parameters
* Every object should extend this model
> Make the Appium model the base response for all responses

- espresso-server/app/src/androidTest/java/io/appium/espressoserver/lib/Handlers/CreateSession.java
- gulpfile.js
- lib/driver.js
- test/functional/driver-e2e-specs.js
Make CreateSession actually launch the specified activity.
The desired capability logic ought to be in generic handling of parameters.
Error handling is still TBD.
> Add activity starting to create session on server

- espresso-server/app/build.gradle
- espresso-server/app/src/androidTest/java/io/appium/espressoserver/lib/Exceptions/DuplicateRouteException.java
- espresso-server/app/src/androidTest/java/io/appium/espressoserver/lib/Exceptions/InvalidStrategyException.java
- espresso-server/app/src/androidTest/java/io/appium/espressoserver/lib/Handlers/Click.java
- espresso-server/app/src/androidTest/java/io/appium/espressoserver/lib/Handlers/Finder.java
- espresso-server/app/src/androidTest/java/io/appium/espressoserver/lib/Handlers/RequestHandler.java
- espresso-server/app/src/androidTest/java/io/appium/espressoserver/lib/Http/Response/BadRequestResponse.java
- espresso-server/app/src/androidTest/java/io/appium/espressoserver/lib/Http/Response/InternalErrorResponse.java
- espresso-server/app/src/androidTest/java/io/appium/espressoserver/lib/Http/Response/NotFoundResponse.java
- espresso-server/app/src/androidTest/java/io/appium/espressoserver/lib/Http/Router.java
- espresso-server/app/src/androidTest/java/io/appium/espressoserver/lib/Http/Server.java
- espresso-server/app/src/androidTest/java/io/appium/espressoserver/lib/Model/Appium.java
- espresso-server/app/src/androidTest/java/io/appium/espressoserver/lib/Model/AppiumStatus.java
- espresso-server/app/src/androidTest/java/io/appium/espressoserver/lib/Model/Element.java
- espresso-server/app/src/androidTest/java/io/appium/espressoserver/lib/Model/Error.java
- espresso-server/app/src/androidTest/java/io/appium/espressoserver/lib/Model/GsonAdapters/AppiumStatusAdapter.java
- espresso-server/app/src/androidTest/java/io/appium/espressoserver/lib/Model/NewSession.java
- espresso-server/app/src/androidTest/java/io/appium/espressoserver/lib/Model/Session.java
- espresso-server/app/src/androidTest/java/io/appium/espressoserver/lib/Model/Strategy.java
- espresso-server/app/src/main/AndroidManifest.xml
* Added all of the different appium status error types
* Also made fixes for problems found by linting tool
> Added appium statuses; made lint fixes

- espresso-server/app/src/androidTest/java/io/appium/espressoserver/lib/Handlers/DeleteSession.java
- espresso-server/app/src/androidTest/java/io/appium/espressoserver/lib/Http/Router.java
- espresso-server/app/src/androidTest/java/io/appium/espressoserver/lib/Model/Session.java
A verify simple route that nullifies the global session id.
> Add route for delete session

- espresso-server/app/src/androidTest/java/io/appium/espressoserver/lib/Exceptions/ElementNotFoundException.java
- espresso-server/app/src/androidTest/java/io/appium/espressoserver/lib/Handlers/Finder.java
- espresso-server/app/src/androidTest/java/io/appium/espressoserver/lib/Handlers/ScrollTo.java
- espresso-server/app/src/androidTest/java/io/appium/espressoserver/lib/Handlers/SendKeys.java
- espresso-server/app/src/androidTest/java/io/appium/espressoserver/lib/Model/Strategy.java
add content description finder
add scrollTo handler
> add content description finder and scrollTo handler

- espresso-server/app/src/androidTest/java/io/appium/espressoserver/lib/Handlers/BaseHandler.java
- espresso-server/app/src/androidTest/java/io/appium/espressoserver/lib/Handlers/Click.java
- espresso-server/app/src/androidTest/java/io/appium/espressoserver/lib/Handlers/CreateSession.java
- espresso-server/app/src/androidTest/java/io/appium/espressoserver/lib/Handlers/DeleteSession.java
- espresso-server/app/src/androidTest/java/io/appium/espressoserver/lib/Handlers/Finder.java
- espresso-server/app/src/androidTest/java/io/appium/espressoserver/lib/Handlers/RequestHandler.java
- espresso-server/app/src/androidTest/java/io/appium/espressoserver/lib/Handlers/ScrollTo.java
- espresso-server/app/src/androidTest/java/io/appium/espressoserver/lib/Handlers/SendKeys.java
- espresso-server/app/src/androidTest/java/io/appium/espressoserver/lib/Handlers/Status.java
- espresso-server/app/src/androidTest/java/io/appium/espressoserver/lib/Http/Response/InternalErrorResponse.java
- espresso-server/app/src/androidTest/java/io/appium/espressoserver/lib/Http/Router.java
Move the param handling to the router. Make base handler to do the session check, etc.
Not the final product, but at least a little DRYer.
> Remove some redundancy in Java

- espresso-server/app/src/androidTest/java/io/appium/espressoserver/lib/http/response/BaseResponse.java
- espresso-server/app/src/androidTest/java/io/appium/espressoserver/lib/http/response/ErrorResponse.java
- espresso-server/app/src/androidTest/java/io/appium/espressoserver/lib/model/SessionParams.java
- espresso-server/app/src/androidTest/java/io/appium/espressoserver/lib/model/Strategy.java
- espresso-server/app/src/test/java/io/appium/espressoserver/ExampleUnitTest.java
* Move field declarations to top of class
* Remove one underscore
* Make on field final
> Codacy fixes

- .travis.yml
- lib/espresso-runner.js
- package.json
- test/functional/desired.js
> Add travis config

- espresso-server/app/build.gradle
- espresso-server/app/src/androidTest/java/io/appium/espressoserver/EspressoServerRunnerTest.java
- espresso-server/app/src/androidTest/java/io/appium/espressoserver/lib/handlers/CreateSession.java
- espresso-server/app/src/androidTest/java/io/appium/espressoserver/lib/handlers/NotYetImplemented.java
- espresso-server/app/src/androidTest/java/io/appium/espressoserver/lib/handlers/exceptions/DuplicateRouteException.java
- espresso-server/app/src/androidTest/java/io/appium/espressoserver/lib/handlers/exceptions/NotYetImplementedException.java
- espresso-server/app/src/androidTest/java/io/appium/espressoserver/lib/http/RouteDefinition.java
- espresso-server/app/src/androidTest/java/io/appium/espressoserver/lib/http/RouteMap.java
- espresso-server/app/src/androidTest/java/io/appium/espressoserver/lib/http/Router.java
- espresso-server/app/src/androidTest/java/io/appium/espressoserver/lib/http/Server.java
- espresso-server/app/src/androidTest/java/io/appium/espressoserver/lib/http/response/BaseResponse.java
* Added not yet implemented handler and exception
* Added every Appium route and made the non-implemented routes call that handler
> Handles routes that aren't implemented

- espresso-server/app/src/androidTest/java/io/appium/espressoserver/lib/handlers/Screenshot.java
- espresso-server/app/src/androidTest/java/io/appium/espressoserver/lib/http/Router.java
- espresso-server/app/src/androidTest/java/io/appium/espressoserver/lib/model/SourceDocument.java
I've confirmed that this works. I ran it in Appium Desktop. 
Side note, the espresso driver does everything we need to run it in Appium Desktop now! (screenshot, source, find by xpath, click, send keys)
> Added screenshot handler

- espresso-server/app/build.gradle
- espresso-server/app/src/androidTest/java/io/appium/espressoserver/lib/model/SourceDocument.java
- espresso-server/app/src/androidTest/java/io/appium/espressoserver/lib/model/ViewAttributesEnum.java
* Renames classNames to simple class names (taken from uiautomator)
* Scrub invalid characters from XML attributes
* @mykola-mokhnach  you were right about the XML problems. I discovered this once I did real device testing.
> Sanitize the XML

- espresso-server/app/src/androidTest/java/io/appium/espressoserver/lib/handlers/Text.java
- espresso-server/app/src/androidTest/java/io/appium/espressoserver/lib/handlers/exceptions/AppiumException.java
- espresso-server/app/src/androidTest/java/io/appium/espressoserver/lib/http/Router.java
- espresso-server/app/src/androidTest/java/io/appium/espressoserver/lib/model/Element.java
- espresso-server/app/src/androidTest/java/io/appium/espressoserver/lib/viewaction/GetText.java
- espresso-server/app/src/androidTest/java/io/appium/espressoserver/lib/viewaction/ViewTextGetter.java
- test/functional/commands/text-e2e-specs.js
* Added a GetText class that takes a view interaction and then hackily gets it's view from it and returns the 'text' attribute
> Implemented the /element/:elementId/text endpoint

- docs/debugging-java-from-node.md
- espresso-server/app/src/androidTest/java/io/appium/espressoserver/lib/handlers/FindElements.java
- espresso-server/app/src/androidTest/java/io/appium/espressoserver/lib/handlers/Finder.java
- espresso-server/app/src/androidTest/java/io/appium/espressoserver/lib/helpers/ViewFinder.java
- espresso-server/app/src/androidTest/java/io/appium/espressoserver/lib/http/Router.java
- espresso-server/app/src/androidTest/java/io/appium/espressoserver/lib/model/Locator.java
- lib/espresso-runner.js
- test/functional/commands/finder-e2e-specs.js
* Added an element handler for /elements endpoint
* Can now locate a list of elements instead of just one
* Refactored element finders into one class called ViewFinder that handles finding both lists of elements and single elements
* Documented how to attach Java debugger when running test from JS context
* Added ENV variable that enables Java debugging
> Added handler for /elements endpoint

- espresso-server/app/src/androidTest/java/io/appium/espressoserver/lib/handlers/exceptions/StaleElementException.java
- espresso-server/app/src/androidTest/java/io/appium/espressoserver/lib/http/Router.java
- espresso-server/app/src/androidTest/java/io/appium/espressoserver/lib/http/Server.java
- espresso-server/app/src/androidTest/java/io/appium/espressoserver/lib/http/response/AppiumResponse.java
- espresso-server/app/src/androidTest/java/io/appium/espressoserver/lib/http/response/ErrorResponse.java
- espresso-server/app/src/androidTest/java/io/appium/espressoserver/lib/model/Element.java
- test/functional/commands/finder-e2e-specs.js
* When calling Element.getById, the Element class checks if the view is still displayed
* If view is not displayed throw StaleElementException
> Throws exception if element is stale

- espresso-server/app/build.gradle
- espresso-server/app/src/androidTest/java/io/appium/espressoserver/lib/handlers/AttributesReader.java
- espresso-server/app/src/androidTest/java/io/appium/espressoserver/lib/http/Router.java
- espresso-server/app/src/androidTest/java/io/appium/espressoserver/lib/model/AppiumParams.java
- espresso-server/app/src/androidTest/java/io/appium/espressoserver/lib/model/ViewElement.java
- espresso-server/build.gradle
- espresso-server/gradle/wrapper/gradle-wrapper.properties
Also, updated Gradle config to work with the recent Android Studio 3 build.
> Add support for /session/:sessionId/element/:elementId/attribute/:name endpoint

- espresso-server/app/src/androidTest/java/io/appium/espressoserver/lib/handlers/Screenshot.java
All other drivers also generate screenshots in PNG format
> Fix the default screenshots format

- espresso-server/app/src/androidTest/java/io/appium/espressoserver/lib/handlers/Clear.java
- espresso-server/app/src/androidTest/java/io/appium/espressoserver/lib/handlers/GetLocationInView.java
- espresso-server/app/src/androidTest/java/io/appium/espressoserver/lib/handlers/GetRect.java
- espresso-server/app/src/androidTest/java/io/appium/espressoserver/lib/http/Router.java
- espresso-server/app/src/androidTest/java/io/appium/espressoserver/lib/model/Rect.java
- espresso-server/app/src/androidTest/java/io/appium/espressoserver/lib/model/ViewElement.java
The /rect endpoint has been introduced by Selenium 3.
> Implement /rect and /location_in_view endpoints

- espresso-server/app/src/androidTest/java/io/appium/espressoserver/lib/handlers/CreateSession.java
- espresso-server/app/src/androidTest/java/io/appium/espressoserver/lib/helpers/Logger.java
- espresso-server/app/src/androidTest/java/io/appium/espressoserver/lib/http/Router.java
- espresso-server/app/src/androidTest/java/io/appium/espressoserver/lib/http/Server.java
Added the separate logger instead of System.out
> Add logger

- espresso-server/app/src/androidTest/java/io/appium/espressoserver/lib/handlers/GetAttribute.java
- espresso-server/app/src/androidTest/java/io/appium/espressoserver/lib/model/SourceDocument.java
- espresso-server/app/src/androidTest/java/io/appium/espressoserver/lib/model/ViewElement.java
This is to make the transition process simpler
> Unify the xml source attributes with UIA output

- espresso-server/app/src/androidTest/java/io/appium/espressoserver/lib/handlers/Finder.java
- espresso-server/app/src/androidTest/java/io/appium/espressoserver/lib/handlers/GetDisplayed.java
- espresso-server/app/src/androidTest/java/io/appium/espressoserver/lib/handlers/GetEnabled.java
- espresso-server/app/src/androidTest/java/io/appium/espressoserver/lib/handlers/GetSelected.java
- espresso-server/app/src/androidTest/java/io/appium/espressoserver/lib/helpers/ViewFinder.java
- espresso-server/app/src/androidTest/java/io/appium/espressoserver/lib/model/SourceDocument.java
- espresso-server/app/src/androidTest/java/io/appium/espressoserver/lib/model/ViewElement.java
This Pr is supposed to solve https://github.com/appium/appium-espresso-driver/issues/57
> Addressing multiple find issues

- lib/driver.js
- package.json
Addresses https://github.com/appium/appium-espresso-driver/issues/72
> Disable Android animations via adb for espresso tests

- espresso-server/app/build.gradle
- espresso-server/app/src/androidTest/java/io/appium/espressoserver/lib/handlers/W3CActions.java
- espresso-server/app/src/androidTest/java/io/appium/espressoserver/lib/helpers/w3c_actions/ActionsConstants.java
- espresso-server/app/src/androidTest/java/io/appium/espressoserver/lib/helpers/w3c_actions/ActionsHelpers.java
- espresso-server/app/src/androidTest/java/io/appium/espressoserver/lib/helpers/w3c_actions/ActionsParseException.java
- espresso-server/app/src/androidTest/java/io/appium/espressoserver/lib/http/Router.java
- espresso-server/app/src/androidTest/java/io/appium/espressoserver/lib/model/W3CActionsParams.java
- espresso-server/build.gradle
Also updated gradle dependencies.
> Backport W3C actions implementation for UIA2 server

- espresso-server/app/src/androidTest/java/io/appium/espressoserver/lib/handlers/ElementScreenshot.java
- espresso-server/app/src/androidTest/java/io/appium/espressoserver/lib/helpers/ScreenshotsHelper.java
- espresso-server/app/src/androidTest/java/io/appium/espressoserver/lib/http/Router.java
Also refactored the stuff under the hood
> Implement element screenshot endpoint

- lib/driver.js
- lib/espresso-runner.js
- package.json
In appium-adb 6+ some method interfaces have been slightly changed. This PR makes them up to date.
> Update appium-adb to version 6.0.1

- espresso-server/AndroidManifest-test.xml
Added package version numbers and sdk versions to the test manifest
> Tune the default manifest

- espresso-server/app/src/androidTest/java/io/appium/espressoserver/lib/handlers/FindElements.java
- espresso-server/app/src/androidTest/java/io/appium/espressoserver/lib/handlers/Finder.java
- espresso-server/app/src/androidTest/java/io/appium/espressoserver/lib/helpers/ViewFinder.java
- espresso-server/app/src/androidTest/java/io/appium/espressoserver/lib/http/Router.java
This adds endpoint handlers for 
```
/session/:sessionId/element/:elementId/element
/session/:sessionId/element/:elementId/elements
```
calls
> Implement subelements lookup

- espresso-server/app/src/androidTest/java/io/appium/espressoserver/lib/handlers/AcceptAlert.java
- espresso-server/app/src/androidTest/java/io/appium/espressoserver/lib/handlers/Clear.java
- espresso-server/app/src/androidTest/java/io/appium/espressoserver/lib/handlers/Click.java
- espresso-server/app/src/androidTest/java/io/appium/espressoserver/lib/handlers/DismissAlert.java
- espresso-server/app/src/androidTest/java/io/appium/espressoserver/lib/handlers/ElementScreenshot.java
- espresso-server/app/src/androidTest/java/io/appium/espressoserver/lib/handlers/GetAlertText.java
- espresso-server/app/src/androidTest/java/io/appium/espressoserver/lib/handlers/SendKeys.java
- espresso-server/app/src/androidTest/java/io/appium/espressoserver/lib/handlers/Source.java
- espresso-server/app/src/androidTest/java/io/appium/espressoserver/lib/handlers/exceptions/ElementNotVisibleException.java
- espresso-server/app/src/androidTest/java/io/appium/espressoserver/lib/handlers/exceptions/InvalidElementStateException.java
- espresso-server/app/src/androidTest/java/io/appium/espressoserver/lib/handlers/exceptions/NoAlertOpenException.java
- espresso-server/app/src/androidTest/java/io/appium/espressoserver/lib/handlers/exceptions/ScreenCaptureException.java
- espresso-server/app/src/androidTest/java/io/appium/espressoserver/lib/helpers/ScreenshotsHelper.java
- espresso-server/app/src/androidTest/java/io/appium/espressoserver/lib/http/Router.java
- espresso-server/app/src/androidTest/java/io/appium/espressoserver/lib/model/AppiumStatus.java
This makes thrown exceptions more specific and helps the server in general to be more compatible to what JSWOWP spec requires.
> Improve error handling

- espresso-server/app/build.gradle
Quite often I get `NoClassDefFoundError` after application activity is started by Espresso. I hope this PR can address the problem according to https://groups.google.com/forum/#!topic/android-test-kit-discuss/fhhSVr_JYW0 https://gist.github.com/rafaelwkerr/9f13f4810d2e713f6476
> Tune exclusions list

- .travis.yml
- package.json
- test/functional/commands/move-to-e2e-specs.js
Some tests are still failing, but they are running now, at least.
> Tweak the build to work

- espresso-server/app/src/androidTest/java/io/appium/espressoserver/lib/handlers/FindElement.java
- espresso-server/app/src/androidTest/java/io/appium/espressoserver/lib/handlers/FindElements.java
- espresso-server/app/src/androidTest/java/io/appium/espressoserver/lib/handlers/Screenshot.java
- espresso-server/app/src/androidTest/java/io/appium/espressoserver/lib/helpers/ViewFinder.java
- espresso-server/app/src/androidTest/java/io/appium/espressoserver/lib/model/SourceDocument.java
- espresso-server/app/src/androidTest/java/io/appium/espressoserver/lib/model/ViewAttributesEnum.java
- espresso-server/app/src/androidTest/java/io/appium/espressoserver/lib/viewaction/ViewGetter.java
- espresso-server/app/src/androidTest/java/io/appium/espressoserver/lib/viewaction/ViewTextGetter.java
- test/functional/commands/source-e2e-specs.js
There's two classes called ViewFinder
Renamed one of them ViewGetter which pulls a view from a ViewInteraction
> Rename viewFinder to ViewGetter

- espresso-server/app/src/androidTest/java/io/appium/espressoserver/lib/handlers/SendKeys.java
- espresso-server/app/src/androidTest/java/io/appium/espressoserver/lib/helpers/StringHelpers.java
- espresso-server/app/src/androidTest/java/io/appium/espressoserver/lib/http/Router.java
- espresso-server/app/src/androidTest/java/io/appium/espressoserver/lib/model/TextParams.java
Addresses https://github.com/appium/ruby_lib/issues/598#issuecomment-392232221
> Try to use replaceText instead of typeText if the latter fails

- espresso-server/app/src/androidTest/java/io/appium/espressoserver/lib/handlers/GetAttribute.java
- espresso-server/app/src/androidTest/java/io/appium/espressoserver/lib/handlers/SendKeys.java
- espresso-server/app/src/androidTest/java/io/appium/espressoserver/lib/handlers/Text.java
- espresso-server/app/src/androidTest/java/io/appium/espressoserver/lib/http/Router.java
- espresso-server/app/src/androidTest/java/io/appium/espressoserver/lib/model/SourceDocument.java
- espresso-server/app/src/androidTest/java/io/appium/espressoserver/lib/model/ViewElement.java
- espresso-server/app/src/androidTest/java/io/appium/espressoserver/lib/model/ViewText.java
- espresso-server/app/src/androidTest/java/io/appium/espressoserver/lib/viewaction/ViewTextGetter.java
CharSequence is an interface, which could contain any instance, which implements it. It would be safer to return a simple String instead. Also, the text getting procedure itself should be common across the code.
See https://github.com/appium/ruby_lib/issues/598#issuecomment-393713265 for more details.
> Update text retrieval algorithm

- espresso-server/app/src/androidTest/java/io/appium/espressoserver/lib/helpers/w3c/models/ActiveInputSources.java
- espresso-server/app/src/androidTest/java/io/appium/espressoserver/lib/helpers/w3c/models/InputSource.java
- espresso-server/app/src/androidTest/java/io/appium/espressoserver/lib/helpers/w3c/state/InputStateInterface.java
- espresso-server/app/src/androidTest/java/io/appium/espressoserver/lib/helpers/w3c/state/InputStateTable.java
- espresso-server/app/src/androidTest/java/io/appium/espressoserver/lib/helpers/w3c/state/KeyInputState.java
- espresso-server/app/src/androidTest/java/io/appium/espressoserver/lib/helpers/w3c/state/PointerInputState.java
- espresso-server/app/src/test/java/io/appium/espressoserver/test/helpers/w3c/InputSourceTest.java
- espresso-server/app/src/test/java/io/appium/espressoserver/test/helpers/w3c/KeyInputStateTest.java
(I'm going to merge this and future commits into the one dpgraham-w3c branch until that one is ready to be merged into master)
* Added state models from W3C spec: https://www.w3.org/TR/webdriver/#input-source-state
* Added PointerInputState, KeyInputState and amended the source states to return default state objects
> W3C input states (17.2)

- espresso-server/app/src/androidTest/java/io/appium/espressoserver/lib/handlers/exceptions/MoveTargetOutOfBoundsException.java
- espresso-server/app/src/androidTest/java/io/appium/espressoserver/lib/handlers/exceptions/NotYetImplementedException.java
- espresso-server/app/src/androidTest/java/io/appium/espressoserver/lib/helpers/w3c/adapter/BaseW3CActionAdapter.java
- espresso-server/app/src/androidTest/java/io/appium/espressoserver/lib/helpers/w3c/adapter/DummyW3CActionAdapter.java
- espresso-server/app/src/androidTest/java/io/appium/espressoserver/lib/helpers/w3c/adapter/EspressoW3CActionAdapter.java
- espresso-server/app/src/androidTest/java/io/appium/espressoserver/lib/helpers/w3c/adapter/W3CActionAdapter.java
- espresso-server/app/src/androidTest/java/io/appium/espressoserver/lib/helpers/w3c/dispatcher/KeyDispatch.java
- espresso-server/app/src/androidTest/java/io/appium/espressoserver/lib/helpers/w3c/dispatcher/PointerDispatch.java
- espresso-server/app/src/androidTest/java/io/appium/espressoserver/lib/helpers/w3c/state/PointerInputState.java
- espresso-server/app/src/androidTest/java/io/appium/espressoserver/lib/http/Router.java
- espresso-server/app/src/test/java/io/appium/espressoserver/test/helpers/w3c/KeyDispatchTest.java
- espresso-server/app/src/test/java/io/appium/espressoserver/test/helpers/w3c/PointerDispatchTest.java
Implemented https://www.w3.org/TR/webdriver/#pointer-actions
> Implement pointer dispatch algorithms

- espresso-server/app/src/androidTest/java/io/appium/espressoserver/lib/helpers/w3c/adapter/BaseW3CActionAdapter.java
- espresso-server/app/src/androidTest/java/io/appium/espressoserver/lib/helpers/w3c/adapter/EspressoW3CActionAdapter.java
- espresso-server/app/src/androidTest/java/io/appium/espressoserver/lib/helpers/w3c/adapter/W3CActionAdapter.java
- espresso-server/app/src/androidTest/java/io/appium/espressoserver/lib/helpers/w3c/dispatcher/PointerDispatch.java
- espresso-server/app/src/androidTest/java/io/appium/espressoserver/lib/helpers/w3c/models/ActionObject.java
- espresso-server/app/src/androidTest/java/io/appium/espressoserver/lib/helpers/w3c/models/ActionSequence.java
- espresso-server/app/src/androidTest/java/io/appium/espressoserver/lib/helpers/w3c/models/Tick.java
- espresso-server/app/src/androidTest/java/io/appium/espressoserver/lib/helpers/w3c/state/InputStateTable.java
- espresso-server/app/src/androidTest/java/io/appium/espressoserver/lib/helpers/w3c/state/KeyInputState.java
- espresso-server/app/src/test/java/io/appium/espressoserver/test/assets/key-actions.json
- espresso-server/app/src/test/java/io/appium/espressoserver/test/helpers/w3c/ActionSequenceTest.java
- espresso-server/app/src/test/java/io/appium/espressoserver/test/helpers/w3c/KeyInputStateTest.java
- espresso-server/app/src/test/java/io/appium/espressoserver/test/helpers/w3c/PointerDispatchTest.java
- espresso-server/app/src/test/java/io/appium/espressoserver/test/helpers/w3c/TickTest.java
(see https://www.w3.org/TR/webdriver/#dispatching-actions)
* Implements `dispatch tick actions`, `compute the tick duration` and `dispatch actions`
> Implement dispatcher algorithm 17.4

- espresso-server/app/src/androidTest/java/io/appium/espressoserver/lib/helpers/w3c/adapter/espresso/AndroidMotionEvent.java
- espresso-server/app/src/androidTest/java/io/appium/espressoserver/lib/helpers/w3c/dispatcher/KeyDispatch.java
- espresso-server/app/src/androidTest/java/io/appium/espressoserver/lib/model/Element.java
> Calculate metaState for pointer events

- espresso-server/app/src/androidTest/java/io/appium/espressoserver/lib/handlers/Keys.java
- espresso-server/app/src/androidTest/java/io/appium/espressoserver/lib/helpers/w3c/models/Actions.java
- espresso-server/app/src/androidTest/java/io/appium/espressoserver/lib/helpers/w3c/models/InputSource.java
- espresso-server/app/src/androidTest/java/io/appium/espressoserver/lib/http/Router.java
- test/functional/driver-e2e-specs.js
* Took the approach of simply creating the equivalent /actions events that /keys endpoint would translate to
> Add /keys endpoint

- .travis.yml
- package.json
- test/functional/commands/touch-e2e-specs.js
Update the touch specs.
1. Use only a single session. This alone moves it from 6 minutes to ~50 seconds locally
2. Stop hardcoding sizes of things, so that the much smaller devices on Travis work.
> Update tests to fix the build

- espresso-server/app/src/androidTest/java/io/appium/espressoserver/lib/model/Strategy.java
- espresso-server/app/src/androidTest/java/io/appium/espressoserver/lib/model/ViewAttributesEnum.java
This will allow to use standard Selenium stuff without adding the extra stuff into client libs
> Add an alias for ByTagName Selenium locator

- espresso-server/app/src/androidTest/java/io/appium/espressoserver/lib/handlers/CreateSession.java
- espresso-server/app/src/androidTest/java/io/appium/espressoserver/lib/handlers/StartActivity.java
- espresso-server/app/src/androidTest/java/io/appium/espressoserver/lib/handlers/exceptions/SessionNotCreatedException.java
Addresses https://gist.github.com/eMTe123/b6e155f2a1fc84eeed524d72a4245c39
> Improve the exception message shown on session startup failure

- espresso-server/app/src/androidTest/java/io/appium/espressoserver/lib/handlers/MobileSwipe.java
- espresso-server/app/src/androidTest/java/io/appium/espressoserver/lib/http/Router.java
- espresso-server/app/src/androidTest/java/io/appium/espressoserver/lib/model/MobileSwipeParams.java
- lib/commands/execute.js
- lib/commands/general.js
- test/functional/commands/mobile-e2e-specs.js
Espresso has swipeUp, swipeDown, swipeLeft and swipeRight commands and they're mentioned in the cheatsheet so they must be important. Added them to the server.
> Add mobile:swipe command

- lib/commands/general.js
Addresses https://github.com/appium/appium-espresso-driver/issues/259
> Add required option names verification

- espresso-server/app/src/androidTest/java/io/appium/espressoserver/lib/handlers/exceptions/MoveTargetOutOfBoundsException.java
- espresso-server/app/src/androidTest/java/io/appium/espressoserver/lib/helpers/w3c/dispatcher/PointerDispatch.java
- test/functional/commands/source-e2e-specs.js
- test/functional/commands/touch-e2e-specs.js
* Fixed broken touch actions that fall out of the viewport for some devices/emulators
* Update move target out of bounds to include the viewport height and viewport width so we can troubleshoot how far out of bounds
> Fix tests, update moveTargetOutOfBounds logging

- .gitignore
- lib/driver.js
- package.json
- test/unit/driver-specs.js
addressed in https://github.com/appium/appium-android-driver/pull/461#issuecomment-435773760
> Add set hide policy

- espresso-server/app/src/androidTest/java/io/appium/espressoserver/lib/model/SourceDocument.java
- espresso-server/app/src/androidTest/java/io/appium/espressoserver/lib/model/ViewElement.java
Addresses https://github.com/appium/appium-espresso-driver/issues/292
> Fix NPE on getting adapter items

- lib/driver.js
Fixes https://github.com/appium/appium-espresso-driver/issues/294
> Add setLocation to NO_PROXY list

- .travis.yml
- test/functional/webview/web-e2e-specs.js
> Add webview tests to Travis

- lib/espresso-runner.js
Addresses https://github.com/appium/appium-espresso-driver/issues/292#issuecomment-439026462
Now we store the package only after successful session init
> Fix server rebuild on application package change

- espresso-server/app/src/androidTest/java/io/appium/espressoserver/lib/handlers/Source.java
- espresso-server/app/src/androidTest/java/io/appium/espressoserver/lib/helpers/ViewFinder.java
- espresso-server/app/src/androidTest/java/io/appium/espressoserver/lib/helpers/XMLHelpers.java
- espresso-server/app/src/androidTest/java/io/appium/espressoserver/lib/model/SourceDocument.java
- espresso-server/app/src/androidTest/java/io/appium/espressoserver/lib/model/ViewAttributesEnum.java
- espresso-server/app/src/androidTest/java/io/appium/espressoserver/lib/viewmatcher/WithXPath.java
This is the port of https://github.com/appium/appium-uiautomator2-server/pull/224
> Switch xpath and source tree implementation to use StAX parser based on XmlPull

- espresso-server/app/src/androidTest/java/io/appium/espressoserver/lib/helpers/ViewFinder.java
- espresso-server/app/src/androidTest/java/io/appium/espressoserver/lib/viewmatcher/WithXPath.java
Addresses https://github.com/appium/appium-espresso-driver/issues/311
> Fix exceptions handling for elements location

- espresso-server/app/src/androidTest/java/io/appium/espressoserver/lib/helpers/ViewFinder.java
Apply more fixes to resolve https://github.com/appium/appium-espresso-driver/issues/311
> Update the detection of nested views

- espresso-server/app/src/androidTest/java/io/appium/espressoserver/lib/model/SourceDocument.java
- espresso-server/app/src/androidTest/java/io/appium/espressoserver/lib/model/ViewElement.java
Addresses https://travis-ci.org/appium/appium-espresso-driver/jobs/460491765#L6095
> Fix NPE in index calculation

- espresso-server/app/src/androidTest/java/io/appium/espressoserver/lib/helpers/w3c/adapter/espresso/EspressoW3CActionAdapter.java
Espresso has a library that calculates the location of a View. Might as well use that instead of our own calculations.
> Use GeneralLocation library to get center point

- espresso-server/app/build.gradle
- espresso-server/app/src/androidTest/java/io/appium/espressoserver/lib/handlers/PointerEventHandler.java
- espresso-server/app/src/androidTest/java/io/appium/espressoserver/lib/helpers/AlertHelpers.java
- espresso-server/app/src/androidTest/java/io/appium/espressoserver/lib/helpers/DeviceInfoHelper.java
- espresso-server/app/src/androidTest/java/io/appium/espressoserver/lib/helpers/StringHelpers.java
- espresso-server/app/src/androidTest/java/io/appium/espressoserver/lib/helpers/XMLHelpers.java
- espresso-server/app/src/androidTest/java/io/appium/espressoserver/lib/helpers/w3c/adapter/espresso/AndroidMotionEvent.java
- espresso-server/app/src/androidTest/java/io/appium/espressoserver/lib/helpers/w3c/adapter/espresso/Helpers.java
- espresso-server/app/src/androidTest/java/io/appium/espressoserver/lib/helpers/w3c/models/Actions.java
- espresso-server/app/src/androidTest/java/io/appium/espressoserver/lib/helpers/w3c/models/InputSource.java
- espresso-server/app/src/androidTest/java/io/appium/espressoserver/lib/helpers/w3c_actions/ActionsHelpers.java
- espresso-server/app/src/androidTest/java/io/appium/espressoserver/lib/http/response/AppiumResponse.java
- espresso-server/app/src/androidTest/java/io/appium/espressoserver/lib/model/ActionsParams.java
- espresso-server/app/src/androidTest/java/io/appium/espressoserver/lib/model/TextParams.java
- espresso-server/app/src/androidTest/java/io/appium/espressoserver/lib/model/ViewText.java
- espresso-server/app/src/androidTest/java/io/appium/espressoserver/lib/viewmatcher/WithXPath.java
https://developer.android.com/jetpack/androidx/migrate
> Make sure all dependencies are imported from AndroidX

- lib/driver.js
IME related commands have `GET` methods as well such as get ime engines
> add get ime

- espresso-server/app/src/androidTest/java/io/appium/espressoserver/lib/helpers/StringHelpers.java
- espresso-server/app/src/androidTest/java/io/appium/espressoserver/lib/model/SourceDocument.java
Addresses https://github.com/appium/appium-espresso-driver/issues/340
> Limit traversal depth and maximum length of xml values to avoid unexpected OOM errors

- espresso-server/app/src/androidTest/java/io/appium/espressoserver/lib/helpers/ViewFinder.java
Addresses https://github.com/appium/appium-espresso-driver/issues/345
> Automatically add package prefix to id selectors

- lib/driver.js
Addresses https://github.com/appium/appium-espresso-driver/issues/345
> Tune noSign capability handling

- lib/driver.js
Related to https://github.com/appium/appium-android-driver/pull/491
> Remove the redundant java version retrieval

- espresso-server/app/build.gradle
- espresso-server/app/src/androidTest/java/io/appium/espressoserver/lib/handlers/CreateSession.java
- espresso-server/app/src/androidTest/java/io/appium/espressoserver/lib/handlers/StartActivity.java
- espresso-server/app/src/androidTest/java/io/appium/espressoserver/lib/helpers/ActivityHelper.java
- espresso-server/app/src/androidTest/java/io/appium/espressoserver/lib/helpers/StringHelpers.java
- espresso-server/app/src/androidTest/java/io/appium/espressoserver/lib/model/SessionParams.java
- espresso-server/app/src/androidTest/java/io/appium/espressoserver/lib/model/StartActivityParams.java
- espresso-server/build.gradle
- espresso-server/gradle/wrapper/gradle-wrapper.properties
https://developer.android.com/guide/components/activities/testing
Also tries to address https://github.com/appium/appium-espresso-driver/issues/376
Do not merge this PR unless it is tested properly. I'm not sure this is going to work in all environements
> Improve the way we start activities

- .npmignore
- test/unit/driver-specs.js
See https://travis-ci.org/appium/appium-espresso-driver/jobs/487263635#L1806
> Add installOrUpgrade to adb stub in unit tests

- test/functional/commands/touch-e2e-specs.js
Small change. One test in this suite is flakey.
> Add retry to scroll tests

- espresso-server/app/src/androidTest/java/io/appium/espressoserver/lib/helpers/StringHelpers.java
- espresso-server/app/src/androidTest/java/io/appium/espressoserver/lib/helpers/ViewsCache.kt
- espresso-server/app/src/androidTest/java/io/appium/espressoserver/lib/model/Element.java
- espresso-server/build.gradle
This is the second try to revamp  the current stuff and to make it nice and easy to read/modify
> Refactor elements cache implementation

- espresso-server/app/src/androidTest/java/io/appium/espressoserver/lib/handlers/GetSessions.kt
- espresso-server/app/src/androidTest/java/io/appium/espressoserver/lib/helpers/KReflectionUtils.kt
- espresso-server/app/src/androidTest/java/io/appium/espressoserver/lib/model/SessionParams.kt
- espresso-server/app/src/test/java/io/appium/espressoserver/test/helpers/KReflectionUtilsTest.kt
- lib/espresso-runner.js
https://github.com/SeleniumHQ/selenium/wiki/JsonWireProtocol requires `/sessions` call to return a list of active session ids along with their capabilities.
> Fix getSessions output

- lib/commands/execute.js
- package.json
Based on https://github.com/appium/appium-android-driver/pull/514
> Add permissions handling mobile endpoints

- lib/driver.js
- test/functional/commands/keyboard-e2e-specs.js
- test/functional/driver-e2e-specs.js
Fixes https://github.com/appium/appium/issues/12414
> Fix name of the EspressoRunner argument

- espresso-server/app/src/androidTest/java/io/appium/espressoserver/lib/http/Router.java
Addresses https://github.com/appium/appium-espresso-driver/issues/442
> Fix alert routes parameter types

- espresso-server/app/src/androidTest/java/io/appium/espressoserver/lib/helpers/ActivityHelper.java
- lib/utils.js
Borrowed from https://android.googlesource.com/platform/frameworks/base/+/master/tools/aapt/Resource.cpp#755
> Update qualifyActivityName algorithm

- lib/commands/general.js
- lib/driver.js
Addresses https://github.com/appium/appium-espresso-driver/issues/451
> Make reset endpoint to properly restore the Espresso server

- espresso-server/app/src/androidTest/java/io/appium/espressoserver/lib/handlers/PerformAutofillDismissal.kt
- espresso-server/app/src/androidTest/java/io/appium/espressoserver/lib/helpers/AutofillHelpers.kt
- espresso-server/app/src/androidTest/java/io/appium/espressoserver/lib/http/RouteMap.java
- espresso-server/app/src/androidTest/java/io/appium/espressoserver/lib/http/Router.java
- espresso-server/app/src/androidTest/java/io/appium/espressoserver/lib/model/Element.kt
- lib/commands/execute.js
- lib/commands/general.js
Based on https://stackoverflow.com/questions/46812716/how-to-disable-the-new-autofill-feature-from-android-oreo-for-espresso-tests
> Add a mobile helper to disable autofill dialog in Android O

- lib/driver.js
to support https://github.com/appium/appium-base-driver/pull/328
> add execute driver to no-proxy list

- lib/utils.js
Addresses https://github.com/appium/appium/issues/13030
> Avoid qualifying the activity name if it is a pattern

- lib/commands/execute.js
- lib/driver.js
- package.json
Based on appium/appium-android-driver#586
> feat: Add mobile commands to start/stop screen streaming

- lib/commands/execute.js
- package.json
https://github.com/appium/appium-android-driver/pull/598
> feat: Add mobile: API to retrieve notifications

- espresso-server/app/src/androidTest/java/io/appium/espressoserver/lib/handlers/CreateSession.kt
- lib/driver.js
> Support #531 skip launching app activity if autoLaunch is set to false

- espresso-server/app/src/androidTest/java/io/appium/espressoserver/lib/handlers/OpenNotifications.kt
- espresso-server/app/src/androidTest/java/io/appium/espressoserver/lib/http/Router.kt
Implement /session/:session_id/appium/device/open_notifications
> implement open_notifications endpoint

- espresso-server/app/src/androidTest/java/io/appium/espressoserver/lib/handlers/CreateSession.kt
- espresso-server/app/src/androidTest/java/io/appium/espressoserver/lib/handlers/MobileBackdoor.kt
- espresso-server/app/src/androidTest/java/io/appium/espressoserver/lib/handlers/StartActivity.kt
- espresso-server/app/src/androidTest/java/io/appium/espressoserver/lib/helpers/ActivityHelpers.kt
- espresso-server/app/src/androidTest/java/io/appium/espressoserver/lib/helpers/IntentHelpers.kt
- espresso-server/app/src/androidTest/java/io/appium/espressoserver/lib/model/StartActivityParams.kt
- espresso-server/app/src/test/java/io/appium/espressoserver/test/helpers/IntentCreationTests.kt
- lib/desired-caps.js
https://github.com/appium/appium-espresso-driver/issues/538
> feat: Add a possibility to provide intentOptions

- espresso-server/app/src/androidTest/java/io/appium/espressoserver/lib/helpers/IntentHelpers.kt
- espresso-server/app/src/test/java/io/appium/espressoserver/test/helpers/IntentCreationTests.kt
- espresso-server/build.gradle
- espresso-server/gradle/wrapper/gradle-wrapper.properties
https://github.com/appium/appium-espresso-driver/issues/541
> feat: Allow to provide multiple values as extra activity params

- lib/driver.js
https://github.com/appium/appium/issues/13989
> feat: Introduce NO_PROXY list for web context

- ci-jobs/templates/android-e2e-template.yml
- lib/driver.js
- package.json
- test/functional/desired.js
Based on https://github.com/appium/appium-android-driver/pull/610
> chore: Update isEmulator detection

- lib/driver.js
- package.json
appium/appium-android-driver#614 for espresso driver.
Need to update appium-android-driver after the PR publishment.
> feat: add ignoreHiddenApiPolicyError

- lib/espresso-runner.js
- package.json
https://github.com/appium/appium-espresso-driver/pull/557#issuecomment-600682613
> fix: Properly sanitise file and directory names

- lib/commands/execute.js
- test/unit/commands/execute-specs.js
Addressing: https://github.com/appium/appium/issues/14116
> feat: include sensorSet to mobile commands

- espresso-server/app/src/androidTest/java/io/appium/espressoserver/lib/helpers/AccessibilityServiceState.kt
- espresso-server/app/src/androidTest/java/io/appium/espressoserver/lib/http/Server.kt
- lib/desired-caps.js
- lib/driver.js
- lib/espresso-runner.js
https://github.com/appium/appium/issues/4910 for Espresso driver.
> feat: add disableSuppressAccessibilityService

- espresso-server/app/src/androidTest/java/io/appium/espressoserver/lib/handlers/CreateSession.kt
- espresso-server/app/src/androidTest/java/io/appium/espressoserver/lib/handlers/StartActivity.kt
- espresso-server/app/src/androidTest/java/io/appium/espressoserver/lib/helpers/ActivityHelpers.kt
- espresso-server/app/src/androidTest/java/io/appium/espressoserver/lib/helpers/ActivityOptionsHelpers.kt
- espresso-server/app/src/androidTest/java/io/appium/espressoserver/lib/model/StartActivityParams.kt
- lib/desired-caps.js
https://github.com/appium/appium-espresso-driver/issues/546
> feat: Add option to startActivity on another display

- lib/commands/execute.js
- package.json
Based on https://github.com/appium/appium-android-driver/pull/623
> feat: Add getDeviceTime endpoint

- lib/commands/execute.js
- package.json
Based on https://github.com/appium/appium-android-driver/pull/630
> feat: Add support for mobile helper related to emulator console commands execution

- lib/commands/execute.js
- package.json
Based on https://github.com/appium/appium-android-driver/pull/634
> feat: Add 'mobile: deleteFile' endpoint

- espresso-server/app/build.gradle
- espresso-server/app/src/androidTest/java/io/appium/espressoserver/lib/helpers/w3c/adapter/espresso/AndroidKeyEvent.java
- espresso-server/app/src/androidTest/java/io/appium/espressoserver/lib/helpers/w3c/adapter/espresso/MotionEventBuilder.java
- espresso-server/app/src/androidTest/java/io/appium/espressoserver/lib/helpers/w3c/adapter/espresso/MultiTouchState.java
- espresso-server/app/src/androidTest/java/io/appium/espressoserver/lib/helpers/w3c/dispatcher/BaseDispatchResult.java
- espresso-server/app/src/androidTest/java/io/appium/espressoserver/lib/helpers/w3c/dispatcher/KeyDispatch.java
- espresso-server/app/src/androidTest/java/io/appium/espressoserver/lib/helpers/w3c/models/ActionObject.java
- espresso-server/app/src/androidTest/java/io/appium/espressoserver/lib/helpers/w3c/models/InputSource.java
- espresso-server/app/src/androidTest/java/io/appium/espressoserver/lib/helpers/w3c/models/Origin.java
- espresso-server/app/src/androidTest/java/io/appium/espressoserver/lib/helpers/w3c/state/ActiveInputSources.java
- espresso-server/app/src/androidTest/java/io/appium/espressoserver/lib/helpers/w3c/state/KeyInputState.java
- espresso-server/app/src/androidTest/java/io/appium/espressoserver/lib/helpers/w3c_actions/ActionsHelpers.java
- espresso-server/app/src/androidTest/java/io/appium/espressoserver/lib/http/Server.kt
- espresso-server/app/src/androidTest/java/io/appium/espressoserver/lib/viewaction/OrientationChange.java
- espresso-server/app/src/androidTest/java/io/appium/espressoserver/lib/viewaction/ScrollTo.java
- espresso-server/app/src/androidTest/java/io/appium/espressoserver/lib/viewaction/UiControllerRunnable.java
- espresso-server/app/src/test/java/io/appium/espressoserver/test/assets/Helpers.java
- espresso-server/app/src/test/java/io/appium/espressoserver/test/helpers/InvocationOperationTest.java
- espresso-server/app/src/test/java/io/appium/espressoserver/test/helpers/w3c/KeyInputStateTest.java
- espresso-server/app/src/test/java/io/appium/espressoserver/test/model/MobileBackdoorMethodTest.java
- espresso-server/build.gradle
- espresso-server/gradle.properties
- espresso-server/gradle/wrapper/gradle-wrapper.properties
Also addresses some warnings that IDEA was complaining to
> chore: Bump component versions

- espresso-server/app/src/androidTest/java/io/appium/espressoserver/lib/helpers/w3c/models/Actions.kt
- espresso-server/app/src/androidTest/java/io/appium/espressoserver/lib/helpers/w3c/models/InputSource.kt
apply returns the class `this`. It can simplify builder class in Kotlin :)
> refactor: use apply for return this

- lib/commands/execute.js
- package.json
Assist https://github.com/appium/appium-android-driver/pull/662 for espresso driver
e.g.
```
=> [{"proc"=>"@webview_devtools_remote_26686",
"webview"=>"WEBVIEW_26686",
"info"=>
{"Android-Package"=>"io.appium.android.apis",
"Browser"=>"Chrome/73.0.3683.90",
"Protocol-Version"=>"1.3",
"User-Agent"=>"Mozilla/5.0 (Linux; Android 9; Android SDK built for x86_64 Build/PSR1.180720.075; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/73.0.3683.90 Mobile Safari/537.36",
"V8-Version"=>"7.3.492.26",
"WebKit-Version"=>"537.36 (@57fb46f3cae300414fb48cb77ed632f3f4ec0c13)",
"webSocketDebuggerUrl"=>"ws://127.0.0.1:10900/devtools/browser"},
"pages"=>
[{"description"=>"{\"attached\":true,\"empty\":false,\"height\":1584,\"screenX\":0,\"screenY\":210,\"visible\":true,\"width\":1080}", …
```
> feat: add mobile:getContexts

- lib/espresso-runner.js
https://github.com/appium/appium-espresso-driver/issues/608
> feat: Make it possible to provide a build config directly from capabilities

- espresso-server/app/src/androidTest/java/io/appium/espressoserver/lib/http/Router.kt
https://github.com/appium/appium-espresso-driver/pull/610#issuecomment-701192125
> chore: Throw better exception in case of NoClassDefFoundError

- espresso-server/app/build.gradle
- espresso-server/app/src/androidTest/java/io/appium/espressoserver/lib/http/Router.kt
- lib/server-builder.js
- lib/utils.js
- test/functional/commands/mobile-e2e-specs.js
- test/unit/server-builder-specs.js
https://github.com/appium/appium-espresso-driver/pull/610#issuecomment-701192125
> refactor: Make com.google.android.material dependency optional

- espresso-server/app/src/androidTest/java/io/appium/espressoserver/EspressoServerRunnerTest.kt
- espresso-server/app/src/androidTest/java/io/appium/espressoserver/lib/handlers/CreateSession.kt
- espresso-server/app/src/androidTest/java/io/appium/espressoserver/lib/handlers/DeleteSession.kt
- espresso-server/app/src/androidTest/java/io/appium/espressoserver/lib/handlers/GetToastVisibility.kt
- espresso-server/app/src/androidTest/java/io/appium/espressoserver/lib/helpers/NotificationListener.kt
- espresso-server/app/src/androidTest/java/io/appium/espressoserver/lib/helpers/ReflectionUtils.kt
- espresso-server/app/src/androidTest/java/io/appium/espressoserver/lib/helpers/UiAutomationWrapper.kt
- espresso-server/app/src/androidTest/java/io/appium/espressoserver/lib/http/Server.kt
- espresso-server/build.gradle
https://github.com/appium/appium-espresso-driver/issues/617
> refactor: Change toasts validation to use OnAccessibilityEventListener

- lib/driver.js
- package.json
Based on https://github.com/appium/appium-adb/pull/557
> feat: Add server packages to Doze whitelist

- espresso-server/gradle/wrapper/gradle-wrapper.properties
> chore: Gradle Version Updated to 6.5

- README.md
- lib/desired-caps.js
There will be more commits, I just want to split them into smaller parts, so it would be easier to review each.
> docs: Improve Espresso readme

- lib/driver.js
Related to https://github.com/appium/appium-uiautomator2-driver/pull/439
> fix: Make sure video recording is stopped on session deletion

- lib/driver.js
- test/unit/driver-specs.js
Related to https://github.com/appium/appium-uiautomator2-driver/pull/440
> fix: Align autoLaunch capability behaviour with iOS

- lib/espresso-runner.js
Related to https://github.com/appium/appium/issues/15226
> fix: Reset instrumentation state before starting a new instance

- index.js
- package.json
it makes no sense to import the whole module for such a simple action
> chore: Remove dependency on yargs

- README.md
- package.json
Should be merged after https://github.com/appium/appium-android-driver/pull/699 is merged
https://github.com/appium/appium-android-driver/pull/699/files#r655874047
> docs: make enableWebviewDetailsCollection true by default

- espresso-server/app/build.gradle.kts
Addresses https://github.com/appium/appium-espresso-driver/issues/681#issuecomment-895049090
> fix: Correct typecast in the build config

- espresso-server/app/src/androidTest/java/io/appium/espressoserver/lib/drivers/AppDriver.kt
- espresso-server/app/src/androidTest/java/io/appium/espressoserver/lib/drivers/ComposeDriver.kt
- espresso-server/app/src/androidTest/java/io/appium/espressoserver/lib/drivers/EspressoDriver.kt
- espresso-server/app/src/androidTest/java/io/appium/espressoserver/lib/handlers/FindElements.kt
- espresso-server/app/src/androidTest/java/io/appium/espressoserver/lib/helpers/ViewFinder.kt
- test/functional/commands/jetpack-compose-e2e-specs.js
Add compose handler to find multiple elements
> feat: add compose handler to find multiple elements

- espresso-server/app/src/androidTest/java/io/appium/espressoserver/lib/handlers/GetDisplayDensity.kt
- espresso-server/app/src/androidTest/java/io/appium/espressoserver/lib/http/Router.kt
- lib/commands/general.js
https://github.com/appium/appium/issues/15929
> refactor: Fetch display density value from Espresso server rather than from adb

- espresso-server/app/src/androidTest/java/io/appium/espressoserver/lib/handlers/MobileBackdoor.kt
- test/functional/commands/mobile-e2e-specs.js
https://github.com/appium/appium/issues/15933
> fix: avoid recursive serialization when result is non primitive

- README.md
- lib/commands/execute.js
- package.json
Based on 
https://github.com/appium/appium-android-driver/pull/708 
https://github.com/appium/appium-android-driver/pull/709
> feat: Add mobile unlock extension

- README.md
- espresso-server/app/build.gradle.kts
- lib/server-builder.js
This PR makes JVM version in build.gradle configurable via capabilities
> feat: Add new options to the config

- lib/driver.js
Addresses https://github.com/appium/appium/issues/16085
> chore: Add fingerprint to the list of NO_PROXY endpoints

- lib/driver.js
https://github.com/appium/appium-uiautomator2-driver/pull/481 for espresso.
> feat: add se log route as no-proxy

- README.md
- lib/commands/execute.js
- package.json
A port of https://github.com/appium/appium-uiautomator2-driver/pull/486
> feat: Add an extension for GPS cache refresh

- package.json
Reverts appium/appium-espresso-driver#733
> Revert "chore(deps-dev): bump appium-chromedriver from 4.28.0 to 5.0.0"

- lib/server-builder.js
- test/unit/server-builder-specs.js
https://github.com/appium/appium-espresso-driver/issues/763
> fix: set gradle command as full path

- README.md
- espresso-server/app/build.gradle.kts
- lib/server-builder.js
I'll update README later.
https://github.com/appium/appium-espresso-driver/issues/781
> feat: allow to set annotation version

- README.md
- lib/commands/execute.js
- lib/driver.js
Similar to https://github.com/appium/appium-uiautomator2-driver/pull/530
> feat: Add mobile wrappers for media-projection-based screen recording

- README.md
similar to https://github.com/appium/appium-uiautomator2-driver/pull/532
> README: Fix minor typo

- README.md
as same as https://github.com/appium/appium-uiautomator2-driver/pull/535
> docs: update readme about script in the app localization

- README.md
The same update https://github.com/appium/appium-uiautomator2-driver/pull/550
> docs: add target sdk version info in autoGrantPermissions

- README.md
- package.json
https://github.com/appium/appium-uiautomator2-driver/pull/554
> feat: add skipping app state check in terminateApp when the given timeout is zero

- espresso-server/app/src/androidTest/java/io/appium/espressoserver/lib/handlers/GetClipboard.kt
- espresso-server/app/src/androidTest/java/io/appium/espressoserver/lib/handlers/SetClipboard.kt
- espresso-server/app/src/androidTest/java/io/appium/espressoserver/lib/helpers/ScreenshotsHelper.kt
Similar to https://github.com/appium/WebDriverAgent/pull/627
> fix: Enforce usage of base64 RFC4648 encoder

- espresso-server/app/src/androidTest/java/io/appium/espressoserver/lib/helpers/ViewFinder.kt
- espresso-server/app/src/androidTest/java/io/appium/espressoserver/lib/viewmatcher/WithXPath.kt
Addresses https://github.com/appium/appium-espresso-driver/issues/829
> fix: Pass correct argument for multiple xpath matches

- .releaserc
- package.json
As same as https://github.com/appium/appium-chromedriver/compare/v5.2.9...v5.2.10 to generate changelog
> chore: update releaserc

- README.md
- espresso-server/app/src/androidTest/java/io/appium/espressoserver/lib/handlers/MobileSwipe.kt
Reimplemented https://github.com/appium/appium-espresso-driver/pull/811 by @jasodhara  with necessary fixes
> feat: Add swipe support in Compose mode

- README.md
UIA2 also can interact with jetpack compose, so addressing it in the compose section might help readers with some points, that are sufficient with UiA2 driver for example.
> docs: address the possibility of uia2 in jetpack compose

- lib/driver.js
As same as https://github.com/appium/appium-uiautomator2-driver/pull/581
> chore: remove unused unicode caps

- README.md
- lib/desired-caps.js
- lib/driver.js
Address https://github.com/appium/appium-espresso-driver/issues/534 and makes animation configurable before launching the AUT.
> feat: add disableWindowAnimation caps

- README.md
- espresso-server/app/src/androidTest/java/io/appium/espressoserver/lib/handlers/UIThreadSynchronizer.kt
- espresso-server/app/src/androidTest/java/io/appium/espressoserver/lib/http/Router.kt
- lib/commands/execute.js
- lib/commands/idling-resources.js
- Expose API to wait for main thread to idle.
- Problem statement outline here https://github.com/appium/appium-espresso-driver/issues/863
> feat: Expose API to Wait For UI Thread

- lib/commands/general.js
https://github.com/appium/java-client/issues/1945
> fix: Add the missing wrapper for mobile: pressKey

- .github/workflows/functional-test.yml
- lib/commands/general.js
https://github.com/appium/appium-espresso-driver/issues/888
> fix: Fix the 'mobile: backgroundApp' functionality

- README.md
- lib/commands/execute.js
- lib/commands/index.js
- lib/commands/screenshot.js
- package.json
Similar to https://github.com/appium/appium-uiautomator2-driver/pull/628
> feat: Add 'mobile: screenshots' extension

- espresso-server/app/src/androidTest/java/io/appium/espressoserver/lib/helpers/CustomFailureHandler.kt
In #895 @mykola-mokhnach disabled screenshots and hierarchy snapshots on failures, but looks like it wasn't enough.
In Espresso [3.5.0-alpha1](https://developer.android.com/jetpack/androidx/releases/test#espresso-3.5.0-alpha01) Google introduced the "Save view hierarchy to a file on failures" feature, which basically dumps whole view hierarchy on failure.
It was added [here](https://github.com/android/android-test/commit/e25a980edfd32bdcb33432bd5a8ae4302678b63c) and later modified [here](https://github.com/android/android-test/commit/49a46f6f366d12626414e3d2a00af89af14fe394).
The issue is that even if it won't save the view hierarchy to the file by default, it would still dump it beforehand. And to dump the view hierarchy it would need to access the views - and this would cause issues on …
> feat: Disable view hierarchy dumping on failures completely

- espresso-server/app/src/androidTest/java/io/appium/espressoserver/lib/helpers/AlertHelpers.kt
https://github.com/appium/appium-espresso-driver/issues/943
> fix: Alert text retrieval

- package.json
to apply appium/appium-android-driver#895
I'll merge once the CI passes
> fix: io.appium.settings process check as the foreground service check

- package.json
as same as https://github.com/appium/appium-uiautomator2-driver/pull/724
> fix: createADB

- README.md
- package.json
https://github.com/appium/appium-uiautomator2-driver/pull/736
I'll merge after CI passes
> feat: add checkVersion option for mobile:installApp

- README.md
- package.json
Similar to https://github.com/appium/appium-uiautomator2-driver/pull/761/
> feat: Add the support of `timeZone` capability

- .github/workflows/functional-test.yml
CI performance is pretty better, yey
> ci: Enable KVM group perms

- .github/workflows/functional-test.yml
- .github/workflows/unit-test.yml
- lib/commands/execute.js
https://github.com/appium/appium-espresso-driver/pull/998 + type fix and tweak functional test yml
> chore: fix type and CI update

- README.md
- package.json
https://github.com/appium/appium-uiautomator2-driver/pull/778
I'll merge after CI passes
> feat: add user option for mobile: isAppInstalled

- espresso-server/app/build.gradle.kts
- espresso-server/build.gradle.kts
Both can be customized by caps, so this should not be a big deal for users, I believe
(Waiting for the CI result)
> feat: bump default gradle plugin to 8.5.0 and target sdk to 34

- README.md
- lib/commands/clipboard.js
- lib/commands/execute.js
- lib/commands/misc.js
- lib/driver.ts
Related to https://github.com/appium/appium-uiautomator2-driver/pull/800
> feat: Add mobile: wrappers to clipboard APIs

- lib/espresso-runner.js
- package.json
This allows to show a proper error message if one tries to start a session with an incompatible server version thus skipping the server build phase.
> feat: Introduce server status validation

- README.md
- package.json
Same as https://github.com/appium/appium-uiautomator2-driver/pull/829
> feat: Document mobile geolocation APIs

- package.json
the same one -> https://github.com/appium/appium-uiautomator2-driver/pull/836
> chore: bump adb to include supporting activities with unicode chars

- test/functional/commands/clipboard-e2e-specs.js
https://github.com/appium/appium-espresso-driver/pull/1038#discussion_r1907910989
> test: use instanceof

- lib/driver.ts
- lib/espresso-runner.js
Related to https://github.com/appium/appium/pull/21021
> fix: Accept reqBasePath proxy option

- package.json
as same as https://github.com/appium/appium-uiautomator2-driver/pull/870
> chore: bump io.appium.settings

- lib/method-map.js
> chore: add deprecated: true for get clipboard

- test/unit/espresso-runner-specs.js
use for...of for better readability in test
> chore: use for...of for better readability in test

- .github/workflows/functional-test.yml
- ci/run-functional-tests.sh
- test/functional/commands/clipboard-e2e-specs.js
- test/functional/commands/contexts-e2e-specs.js
- test/functional/commands/element-values-e2e-specs.js
- test/functional/commands/find-e2e-specs.js
- test/functional/commands/jetpack-componse-element-values-e2e-specs.js
- test/functional/commands/jetpack-compose-attributes-e2e-specs.js
- test/functional/commands/jetpack-compose-e2e-specs.js
- test/functional/commands/jetpack-compose-source-e2e-specs.js
Support https://github.com/appium/appium/issues/21426 more...
> test: enable e2e more

- ci/run-functional-tests.sh
- test/functional/webview/web-e2e-specs.js
- test/functional/webview/webatoms-e2e-specs.js
Part of https://github.com/appium/appium/issues/21426
> test: update webviews
