appium/appium-espresso-driver

- README.md
- espresso-server/AndroidManifest-test.xml
- espresso-server/app/build.gradle
- espresso-server/app/proguard-rules.pro
- espresso-server/app/src/androidTest/java/io/appium/espressoserver/EspressoServerRunnerTest.java
- espresso-server/app/src/androidTest/java/io/appium/espressoserver/Http/AppiumResponse.java
- espresso-server/app/src/androidTest/java/io/appium/espressoserver/Http/Server.java
- espresso-server/app/src/main/java/io/appium/espressoserver/MainActivity.java
- lib/driver.js
- lib/espresso-runner.js
- test/functional/driver-e2e-specs.js
Wire in the espresso server and add the first functional test. Everything is hardcoded right now, but this gives a starting place to begin working on the espress-server handlers without needing to do a bunch of manual work.
Run a test like `gulp transpile && mocha -t 60000 build/test/functional/driver-e2e-specs.js`
> Initial working session creation

- lib/desired-caps.js
- lib/driver.js
- lib/espresso-runner.js
- package.json
- test/.jshintrc
- test/functional/desired.js
- test/functional/driver-e2e-specs.js
- test/functional/helpers/session.js
If we already have an espresso server apk with the correct version and instrumented for the correct package, we don't need to build it again.
But we want to be able to test changes we've made in development, so add the internal cap `forceEspressoRebuild` to allow us to blow away the one that is already there.
Also add the pre-commit hooks and fix some linting issues.
> Only rebuild server if necessary

- lib/espresso-runner.js
Add base designation (set to empty string) so we don't have `/wd/hub` in proxying to espresso server on device.
> Fix base so we can proxy to the espresso server

- espresso-server/app/src/androidTest/java/io/appium/espressoserver/lib/Handlers/Status.java
- espresso-server/app/src/androidTest/java/io/appium/espressoserver/lib/Http/Router.java
In order to make sure the server is running we use the `/status` endpoint.
> Add very simple /status handler so driver can communicate

- espresso-server/app/src/androidTest/java/io/appium/espressoserver/lib/Handlers/Click.java
- espresso-server/app/src/androidTest/java/io/appium/espressoserver/lib/Handlers/SendKeys.java
- test/functional/commands/keyboard-e2e-specs.js
This introduces a lot of redundancy around parameters handling that will have to be refactored, and there is the weirdness with NanoHTTPD sometimes failing to understand the method.
But it's a functional test that finds an element, clicks it, and types.
> Some warts, but a running e2e test that does stuff

- lib/espresso-runner.js
- test/unit/espresso-runner-specs.js
Stop `await`ing the `exec` of the instrumentation process. This makes error handling a bit wonky, but has the advantage of stripping 20s off each session.
> Remove 20s delay when creating instrumentation process

- espresso-server/app/src/androidTest/java/io/appium/espressoserver/lib/handlers/CreateSession.java
- espresso-server/app/src/androidTest/java/io/appium/espressoserver/lib/model/Session.java
* Made it so that you can’t instantiate Session, you can only call `createGlobalSession`, `deleteGlobalSession` and `getGlobalSessionID` from static context
* `createGlobalSession` returns an instance of Session with just an `id` field. This object is needed for GSON serialization.
* If `createGlobalSession` is called while a session is in progress, throws an exception. We can only run one at a time.
* This fixes a Codacy complaint of static variable being accessed inside of a constructor.
> Edit Session class

- espresso-server/app/src/androidTest/java/io/appium/espressoserver/EspressoServerRunnerTest.java
- espresso-server/app/src/androidTest/java/io/appium/espressoserver/lib/exceptions/DuplicateRouteException.java
- espresso-server/app/src/androidTest/java/io/appium/espressoserver/lib/handlers/Click.java
- espresso-server/app/src/androidTest/java/io/appium/espressoserver/lib/handlers/DeleteSession.java
- espresso-server/app/src/androidTest/java/io/appium/espressoserver/lib/handlers/ScrollTo.java
- espresso-server/app/src/androidTest/java/io/appium/espressoserver/lib/handlers/SendKeys.java
- espresso-server/app/src/androidTest/java/io/appium/espressoserver/lib/handlers/Status.java
- espresso-server/app/src/androidTest/java/io/appium/espressoserver/lib/http/RouteDefinition.java
- espresso-server/app/src/androidTest/java/io/appium/espressoserver/lib/http/RouteMap.java
- espresso-server/app/src/androidTest/java/io/appium/espressoserver/lib/http/Router.java
- espresso-server/app/src/androidTest/java/io/appium/espressoserver/lib/http/Server.java
* Codacy was complaining about the complexity of Router so figured I’d fix it up now
* Add RouteDefinition class which stores the routing uri, the test regex to match incoming routes against, the HTTP method, the parameter class and the handler
* RouteDefinition can check if an incoming URI is a match against it’s own testRegex, and can return URI Params of an incoming URI as a HashMap
* Uses HashMap instead of ConcurrentHashMap because the writing is all done at the beginning and the rest are just reads, therefore it is thread-safe
* Add RouteMap class which contains all of the route definitions in a Map that maps HTTP method to another Map that maps the URI to the RouteDefinition
* When an incoming URL comes into Router.java, it checks RouteMap for a matching RouteDefinition and if it …
> Move routing logic into separate classes

- espresso-server/app/src/androidTest/java/io/appium/espressoserver/EspressoServerRunnerTest.java
- espresso-server/app/src/androidTest/java/io/appium/espressoserver/lib/http/RouteMap.java
- espresso-server/app/src/androidTest/java/io/appium/espressoserver/lib/http/Router.java
- espresso-server/lint.xml
* Added a meaningless assertion to test to avoid warning
* Suppress "unchecked"  warning in Router.java because it's unavoidable
* Ignore linters 'WeakerAccess' check because lint conflicts with Codacy
* Don't make addRoute package-private
> Get codacy to A+

- espresso-server/app/src/androidTest/java/io/appium/espressoserver/lib/handlers/CreateSession.java
- espresso-server/app/src/androidTest/java/io/appium/espressoserver/lib/handlers/GetSession.java
- espresso-server/app/src/androidTest/java/io/appium/espressoserver/lib/handlers/GetSessions.java
- espresso-server/app/src/androidTest/java/io/appium/espressoserver/lib/http/RouteMap.java
- espresso-server/app/src/androidTest/java/io/appium/espressoserver/lib/http/Router.java
- espresso-server/app/src/androidTest/java/io/appium/espressoserver/lib/model/Session.java
* Instead of a static global session ID have a static instance of Session which contains the ID and the desiredCapabilities
* Refactored Session and other methods that use Session to use this new format
* Added routes GET /session/:sessionId and GET /sessions
* Fixed bug in RouteMap; wasn't narrowing down route matches by method
> Save desiredCapabilities with global session

- espresso-server/app/src/androidTest/java/io/appium/espressoserver/lib/http/Router.java
- espresso-server/app/src/androidTest/java/io/appium/espressoserver/lib/http/Server.java
* There appeared to be a race condition that was causing multiple routes to have the same POST body (Isaac had this problem during the hack week)
* This way appears to fix it and is cleaner too
> Override different serve definition in nanohttpd

- espresso-server/app/src/androidTest/java/io/appium/espressoserver/lib/model/SourceDocument.java
- espresso-server/app/src/androidTest/java/io/appium/espressoserver/lib/viewmatcher/WithXPath.java
* Changed SourceDocument so that when it queries the XML it gets _all_ of the matching views
* Changed withXpath so that you can optionally provide and index to match just one of the views
* This is intended to be used in a future change where we can get a list of elements instead of just one
> Can match list of XPaths instead of just one

- .npmignore
and it's generating the module to be more than 100MB
> add gradle build files to gitignore, there's no need for this files(98% sure) 

- .npmignore
The npm package is down significantly (from 111Mb to ~76) but can be reduced further.
> Ignore more files for npm

- espresso-server/app/build.gradle
- espresso-server/app/src/androidTest/java/io/appium/espressoserver/lib/handlers/AcceptAlert.java
- espresso-server/app/src/androidTest/java/io/appium/espressoserver/lib/handlers/AlertText.java
- espresso-server/app/src/androidTest/java/io/appium/espressoserver/lib/handlers/DismissAlert.java
- espresso-server/app/src/androidTest/java/io/appium/espressoserver/lib/handlers/GetAlertText.java
- espresso-server/app/src/androidTest/java/io/appium/espressoserver/lib/http/Router.java
- espresso-server/gradle/wrapper/gradle-wrapper.properties
Espresso is unable to handle things outside the application sandbox, for example system notifications or security alerts. I've added basic UIA2 integration as described in http://qathread.blogspot.de/2015/05/espresso-uiautomator-perfect-tandem.html in order to improve the state of things.
> Add handlers for dialogs/alerts

- espresso-server/app/src/androidTest/java/io/appium/espressoserver/lib/handlers/FindActive.java
- espresso-server/app/src/androidTest/java/io/appium/espressoserver/lib/helpers/ViewFinder.java
- espresso-server/app/src/androidTest/java/io/appium/espressoserver/lib/http/Router.java
- espresso-server/app/src/androidTest/java/io/appium/espressoserver/lib/model/AppiumParams.java
There are both W3C and non-W3C routes
> Add handler for `/session/:sessionId/element/active` endpoint

- espresso-server/app/src/androidTest/java/io/appium/espressoserver/lib/model/Session.java
This fixes a problem when it is not possible to start a new session unless the server is killed if the previous one has not been terminated properly.
> Recreate a session by default

- espresso-server/app/src/androidTest/java/io/appium/espressoserver/lib/handlers/Clear.java
- espresso-server/app/src/androidTest/java/io/appium/espressoserver/lib/handlers/Click.java
- espresso-server/app/src/androidTest/java/io/appium/espressoserver/lib/handlers/ElementScreenshot.java
- espresso-server/app/src/androidTest/java/io/appium/espressoserver/lib/handlers/FindActive.java
- espresso-server/app/src/androidTest/java/io/appium/espressoserver/lib/handlers/FindElement.java
- espresso-server/app/src/androidTest/java/io/appium/espressoserver/lib/handlers/FindElements.java
- espresso-server/app/src/androidTest/java/io/appium/espressoserver/lib/handlers/GetAttribute.java
- espresso-server/app/src/androidTest/java/io/appium/espressoserver/lib/handlers/GetDisplayed.java
- espresso-server/app/src/androidTest/java/io/appium/espressoserver/lib/handlers/GetEnabled.java
- espresso-server/app/src/androidTest/java/io/appium/espressoserver/lib/handlers/GetLocation.java
- espresso-server/app/src/androidTest/java/io/appium/espressoserver/lib/handlers/GetLocationInView.java
- espresso-server/app/src/androidTest/java/io/appium/espressoserver/lib/handlers/GetName.java
- espresso-server/app/src/androidTest/java/io/appium/espressoserver/lib/handlers/GetOrientation.java
- espresso-server/app/src/androidTest/java/io/appium/espressoserver/lib/handlers/GetRect.java
- espresso-server/app/src/androidTest/java/io/appium/espressoserver/lib/handlers/GetSelected.java
- espresso-server/app/src/androidTest/java/io/appium/espressoserver/lib/handlers/GetSize.java
- espresso-server/app/src/androidTest/java/io/appium/espressoserver/lib/handlers/MoveTo.java
- espresso-server/app/src/androidTest/java/io/appium/espressoserver/lib/handlers/SendKeys.java
- espresso-server/app/src/androidTest/java/io/appium/espressoserver/lib/handlers/SetOrientation.java
- espresso-server/app/src/androidTest/java/io/appium/espressoserver/lib/handlers/Text.java
- espresso-server/app/src/androidTest/java/io/appium/espressoserver/lib/helpers/ViewFinder.java
- espresso-server/app/src/androidTest/java/io/appium/espressoserver/lib/helpers/w3c_actions/ActionsHelpers.java
- espresso-server/app/src/androidTest/java/io/appium/espressoserver/lib/model/Element.java
- espresso-server/app/src/androidTest/java/io/appium/espressoserver/lib/viewmatcher/WithView.java
- package.json
- test/functional/commands/find-e2e-specs.js
* Updated the element finding logic so that instead of getting View Interactions it gets the actual Views
* Updated the Element.java class to cache the actual views
* The reasoning for this is that it appears that viewInteractions become stale after using them once, so you can't operate on an "Element" more than once
* @jlipps I think  this may solve your issue with finding elements too
> Cache elements by view instead of view interaction

- lib/driver.js
With current Espresso driver, we wasn't able to create W3C session even the desired capability was same as `uiautomator2` which could work as W3C session.
(I faced when fixing https://github.com/appium/appium-espresso-driver/pull/121)
Couldn't create a W3C session since the `createSession` handle the caps as `MJSONWP` everytime.
```
[HTTP] --> POST /wd/hub/session
[HTTP] {"desiredCapabilities":{"platformName":"android","automationName":"espresso","app":"/Users/kazuaki/GitHub/ruby_lib_core/test/functional/app/api.apk","platformVersion":"8.1.0","deviceName":"Android Emulator","appPackage":"io.appium.android.apis","appActivity":"io.appium.android.apis.ApiDemos","unicodeKeyboard":true,"resetKeyboard":true,"newCommandTimeout":300},"capabilities":{"alwaysMatch":{"platformName":"android","appium: …
```
> fix creating w3c session

- espresso-server/app/src/androidTest/java/io/appium/espressoserver/lib/handlers/CreateSession.java
- espresso-server/app/src/androidTest/java/io/appium/espressoserver/lib/handlers/StartActivity.java
- espresso-server/app/src/androidTest/java/io/appium/espressoserver/lib/http/Router.java
- espresso-server/app/src/androidTest/java/io/appium/espressoserver/lib/model/StartActivityParams.java
- package.json
- test/functional/driver-e2e-specs.js
* Added the `start_activity` endpoint
* Moved startActivity into a common helper method
* Fixed one of the tests. It was trying to open a non-existent activity
* NOTE: I don't think we'll ever be able to use `appPackage` in Espresso Driver. Espresso only deals with the App-under-test
(connected to: https://github.com/appium/appium/issues/8670)
> startActivity

- espresso-server/app/src/androidTest/java/io/appium/espressoserver/lib/handlers/GetAttribute.java
- espresso-server/app/src/androidTest/java/io/appium/espressoserver/lib/helpers/ViewFinder.java
- espresso-server/app/src/androidTest/java/io/appium/espressoserver/lib/http/Router.java
- espresso-server/app/src/androidTest/java/io/appium/espressoserver/lib/model/SourceDocument.java
- espresso-server/app/src/androidTest/java/io/appium/espressoserver/lib/model/ViewAttributesEnum.java
- test/functional/commands/find-e2e-specs.js
- test/functional/commands/keyboard-e2e-specs.js
* When locating an element by accessibility ID, if it isn't found on the first time, try using onData to see if it can be matched with a Hamcrest matcher and scrolled into view (see https://medium.com/google-developers/adapterviews-and-espresso-f4172aa853cf for info on how `onData` works)
* Added `adapter-type` and `adapters` as an attribute to source. This was from a previous experimental branch I worked on. I think in the future I'd like to use a Hamcrest matcher strategy for locating elements so we have other ways to target elements that aren't visible
* Added a test for finding an element that is off the screen (has an accessibility ID called WebView which is the bottom of the list)
> Make accessibility selector scroll into view

- espresso-server/app/src/androidTest/java/io/appium/espressoserver/lib/helpers/w3c/models/ActionObject.java
- espresso-server/app/src/androidTest/java/io/appium/espressoserver/lib/helpers/w3c/models/ActionSequence.java
- espresso-server/app/src/androidTest/java/io/appium/espressoserver/lib/helpers/w3c/models/ActiveInputSources.java
- espresso-server/app/src/androidTest/java/io/appium/espressoserver/lib/helpers/w3c/models/InputSource.java
- espresso-server/app/src/androidTest/java/io/appium/espressoserver/lib/helpers/w3c/models/Tick.java
- espresso-server/app/src/androidTest/java/io/appium/espressoserver/lib/helpers/w3c/models/W3CActions.java
- espresso-server/app/src/androidTest/java/io/appium/espressoserver/lib/helpers/w3c/state/InputStateTable.java
- espresso-server/app/src/test/java/io/appium/espressoserver/test/assets/Helpers.java
- espresso-server/app/src/test/java/io/appium/espressoserver/test/assets/key-actions.json
- espresso-server/app/src/test/java/io/appium/espressoserver/test/assets/multi-touch-actions.json
- espresso-server/app/src/test/java/io/appium/espressoserver/test/helpers/w3c/ActionSequenceTest.java
- espresso-server/app/src/test/java/io/appium/espressoserver/test/helpers/w3c/InputSourceTest.java
- espresso-server/app/src/test/java/io/appium/espressoserver/test/helpers/w3c/KeyInputStateTest.java
- espresso-server/app/src/test/java/io/appium/espressoserver/test/helpers/w3c/W3CActionsTest.java
- test/functional/commands/source-e2e-specs.js
* Implement actions processors based on algorithms specified in [17.3](https://www.w3.org/TR/webdriver/#processing-actions-requests)
* Added an 'ActionObject' class which is the end result of an 'action item' being processed
* Wrote the 'processing' algorithms specified in 17.3... made all of them stateless to simplify writing unit tests
* Added an 'ActionSequence' object which takes all of the action items in a W3C `/actions` payload and creates the transpose of the Actions which is a List of 'Ticks'. A tick is an object that has a list of Action Objects that are to be executed simultaneously.
> W3C Action Processor

- lib/desired-caps.js
- lib/driver.js
- lib/espresso-runner.js
- test/unit/espresso-runner-specs.js
`SubProcess` allows us to have a handle on the running instrumentation process, while `exec` is meant to be fire-and-forget.
Finally fix #124 in Travis.
> Switch to SubProcess for better control

- .travis.yml
- README.md
- espresso-server/AndroidManifest-test.xml
- lib/espresso-runner.js
- test/functional/commands/find-e2e-specs.js
- test/functional/commands/keyboard-e2e-specs.js
- test/functional/commands/move-to-e2e-specs.js
- test/functional/commands/size-e2e-specs.js
- test/functional/commands/source-e2e-specs.js
- test/functional/desired.js
- test/functional/driver-e2e-specs.js
Un-quarantine, and clean up, all the tests except two:
1. [move-to](https://github.com/appium/appium-espresso-driver/blob/master/test/functional/commands/move-to-e2e-specs.js) - I can't figure out what this is supposed to do. But it doesn't work as written.
1. [react-native source](https://github.com/appium/appium-espresso-driver/blob/master/test/functional/commands/source-e2e-specs.js#L42-L53) - missing react native app as asset, which I presume is on the @dpgraham's computer, since he [added the test](https://github.com/appium/appium-espresso-driver/pull/125/files).
> Run remaining tests in Travis

- espresso-server/app/src/androidTest/java/io/appium/espressoserver/lib/helpers/w3c/adapter/BaseW3CActionAdapter.java
- espresso-server/app/src/androidTest/java/io/appium/espressoserver/lib/helpers/w3c/adapter/EspressoW3CActionAdapter.java
- espresso-server/app/src/androidTest/java/io/appium/espressoserver/lib/helpers/w3c/adapter/W3CActionAdapter.java
- espresso-server/app/src/androidTest/java/io/appium/espressoserver/lib/helpers/w3c/dispatcher/BaseDispatchResult.java
- espresso-server/app/src/androidTest/java/io/appium/espressoserver/lib/helpers/w3c/dispatcher/DispatchPointerMoveResult.java
- espresso-server/app/src/androidTest/java/io/appium/espressoserver/lib/helpers/w3c/dispatcher/PointerDispatch.java
- espresso-server/app/src/androidTest/java/io/appium/espressoserver/lib/helpers/w3c/models/ActionObject.java
- espresso-server/app/src/androidTest/java/io/appium/espressoserver/lib/helpers/w3c/models/ActionSequence.java
- espresso-server/app/src/androidTest/java/io/appium/espressoserver/lib/helpers/w3c/models/Tick.java
- espresso-server/app/src/androidTest/java/io/appium/espressoserver/lib/helpers/w3c/state/InputStateTable.java
- espresso-server/app/src/androidTest/java/io/appium/espressoserver/lib/http/Server.java
- espresso-server/app/src/androidTest/java/io/appium/espressoserver/lib/viewaction/ViewGetter.java
- espresso-server/app/src/test/java/io/appium/espressoserver/test/helpers/w3c/PointerDispatchTest.java
- espresso-server/app/src/test/java/io/appium/espressoserver/test/helpers/w3c/TickTest.java
* Pointer move events were being called on a separate thread, which Espresso doesn't allow (must be main thread)
* Updated the logic so that the callable returns a class that has a `perform` method that gets called
* The perform method gets called on the main thread instead of on the thread
> Run pointer move on main thread

- espresso-server/app/src/androidTest/java/io/appium/espressoserver/lib/handlers/GetAttribute.java
- espresso-server/app/src/androidTest/java/io/appium/espressoserver/lib/helpers/ViewFinder.java
- espresso-server/app/src/androidTest/java/io/appium/espressoserver/lib/model/SourceDocument.java
- espresso-server/app/src/androidTest/java/io/appium/espressoserver/lib/model/Strategy.java
- espresso-server/app/src/androidTest/java/io/appium/espressoserver/lib/model/ViewAttributesEnum.java
- espresso-server/app/src/androidTest/java/io/appium/espressoserver/lib/model/ViewElement.java
Add custom selector that targets elements by the [View Tag](https://developer.android.com/reference/android/view/View)
(related to: https://github.com/appium/appium/issues/6025)
> viewtag selector strategy

- espresso-server/app/build.gradle
- espresso-server/app/src/androidTest/java/io/appium/espressoserver/lib/handlers/MultiTouchAction.java
- espresso-server/app/src/androidTest/java/io/appium/espressoserver/lib/handlers/MultiTouchActionsParams.java
- espresso-server/app/src/androidTest/java/io/appium/espressoserver/lib/handlers/TouchAction.java
- espresso-server/app/src/androidTest/java/io/appium/espressoserver/lib/handlers/TouchActionsParams.java
- espresso-server/app/src/androidTest/java/io/appium/espressoserver/lib/helpers/w3c/adapter/espresso/AndroidMotionEvent.java
- espresso-server/app/src/androidTest/java/io/appium/espressoserver/lib/helpers/w3c/adapter/espresso/EspressoW3CActionAdapter.java
- espresso-server/app/src/androidTest/java/io/appium/espressoserver/lib/helpers/w3c/adapter/espresso/MultiTouchState.java
- espresso-server/app/src/androidTest/java/io/appium/espressoserver/lib/helpers/w3c/dispatcher/PointerDispatch.java
- espresso-server/app/src/androidTest/java/io/appium/espressoserver/lib/helpers/w3c/models/ActionObject.java
- espresso-server/app/src/androidTest/java/io/appium/espressoserver/lib/helpers/w3c/models/ActionSequence.java
- espresso-server/app/src/androidTest/java/io/appium/espressoserver/lib/helpers/w3c/models/Actions.java
- espresso-server/app/src/androidTest/java/io/appium/espressoserver/lib/helpers/w3c/models/InputSource.java
- espresso-server/app/src/androidTest/java/io/appium/espressoserver/lib/helpers/w3c/processor/PointerProcessor.java
- espresso-server/app/src/androidTest/java/io/appium/espressoserver/lib/helpers/w3c/state/InputStateTable.java
- espresso-server/app/src/androidTest/java/io/appium/espressoserver/lib/http/Router.java
- espresso-server/app/src/androidTest/java/io/appium/espressoserver/lib/model/TouchAction.java
- espresso-server/app/src/test/java/io/appium/espressoserver/test/model/TouchActionTest.java
- espresso-server/gradle/wrapper/gradle-wrapper.properties
- test/functional/commands/touch-e2e-specs.js
* Add touch and multi touch endpoints
* The approach is to just deserialize the touch actions payload and then convert the TouchAction into a W3C action
* Made it so that each TouchAction had three events (for press/tap/longpress it's `move -> down -> pause`).... `move`, `wait` and `cancel` have one corresponding but they're padded by `pause` with duration 0 (no-op) events so that multi touch actions are synchronized
* Other changes
* Don't check that x,y is positive.... we can have negative x,y relative to element/pointer
* Add tests for W3C multi touch (they work!)
* Make the callable in pointer move use Thread.sleep and not SystemClock or the UiController sleep methods 
* Changed sleep method to use `uiController.loopMainThreadForAtLeast` instead of `SystemClock.sleep`. …
> Add touch/ and touch/multi endpoints

- espresso-server/app/src/androidTest/java/io/appium/espressoserver/lib/helpers/w3c/adapter/espresso/AndroidMotionEvent.java
- espresso-server/app/src/androidTest/java/io/appium/espressoserver/lib/helpers/w3c/adapter/espresso/EspressoW3CActionAdapter.java
- espresso-server/app/src/androidTest/java/io/appium/espressoserver/lib/helpers/w3c/adapter/espresso/MotionEventBuilder.java
* Checks if the device has a touch screen, and if it does assume
mouse events are to be converted to touch
* This is because some clients only do mouse and we want those clients
to still be usable on touchscreen
* Also
* Check downEvent is null before setting 'source' on pointer event. Pointer events don't always have
* Improved logging for 'inject' event exception. Inject event always means it was outside the viewport
> Convert mouse to touch events if touchscreen device

- espresso-server/app/src/androidTest/java/io/appium/espressoserver/lib/handlers/PerformAction.java
- espresso-server/app/src/androidTest/java/io/appium/espressoserver/lib/helpers/w3c/dispatcher/PointerDispatch.java
- espresso-server/app/src/androidTest/java/io/appium/espressoserver/lib/helpers/w3c/models/InputSource.java
- espresso-server/app/src/androidTest/java/io/appium/espressoserver/lib/helpers/w3c/state/InputStateTable.java
- espresso-server/app/src/androidTest/java/io/appium/espressoserver/lib/helpers/w3c/state/PointerInputState.java
- espresso-server/app/src/androidTest/java/io/appium/espressoserver/lib/http/Router.java
- espresso-server/app/src/test/java/io/appium/espressoserver/test/helpers/w3c/PointerDispatchTest.java
- espresso-server/app/src/test/java/io/appium/espressoserver/test/helpers/w3c/ProcessorTest.java
- espresso-server/app/src/test/java/io/appium/espressoserver/test/helpers/w3c/TickTest.java
* input state didn't have a type before so it was maintaining the state by touch only
* This was causing wrong events to be dispatched
* Also
* Fixed typo 'peformActions'
* Removed test that checks that exception thrown if negative x,y actions... negative x, y is fine because it might be relative to a pointer or element
> Fix: Add 'pointerType' (touch, mouse, stylus) to inputState

- espresso-server/app/src/androidTest/java/io/appium/espressoserver/lib/helpers/w3c/adapter/espresso/EspressoW3CActionAdapter.java
- test/functional/commands/touch-e2e-specs.js
* For now, we should convert all MOUSE actions to TOUCH to support Selenium clients
* We may need to revisit it in the future, but this keeps it consistent with other driver implementations
> Convert mouse actions to touch

- package.json
Fix https://github.com/appium/appium/issues/11525#issuecomment-431633469
The cause is missing `espresso-server/AndroidManifest-test.xml` in npm package, it looks.
> fix missing manifest

- lib/driver.js
These endpoints are implemented in the downstream server, so they should be proxied.
Addresses https://github.com/appium/appium-espresso-driver/issues/260
> Remove alert endpoints from NO_PROXY list

- lib/espresso-runner.js
It might be that the target package is changed, so then we need to properly refresh the server apk. Unfortunately dumpsys says nothing about the target package, so we need to keep the target package value elsewhere to know when the server reinstall is needed
Addresses https://github.com/appium/appium-espresso-driver/issues/258
> Properly refresh the server package if the actual package is changed

- lib/commands/general.js
XCUI-driver allows element and elementId. 
This PR allows espresso driver to accept both element and elementId to drivers consistent.
Related Issue: https://github.com/appium/appium-espresso-driver/issues/259
> respect element and elementId for mobile:swipe

- espresso-server/app/src/androidTest/java/io/appium/espressoserver/EspressoServerRunnerTest.java
- espresso-server/app/src/androidTest/java/io/appium/espressoserver/lib/handlers/DeleteSession.java
- espresso-server/app/src/androidTest/java/io/appium/espressoserver/lib/http/Server.java
This PR should enable the server to shutdown graceful.
Should fix #258 `EADDRINUSE (Address already in use)` issue.
> Implemented Delete Session Handling

- espresso-server/app/src/androidTest/java/io/appium/espressoserver/lib/helpers/w3c/adapter/DummyW3CActionAdapter.java
- espresso-server/app/src/androidTest/java/io/appium/espressoserver/lib/helpers/w3c/adapter/W3CActionAdapter.java
- espresso-server/app/src/androidTest/java/io/appium/espressoserver/lib/helpers/w3c/adapter/espresso/EspressoW3CActionAdapter.java
- espresso-server/app/src/androidTest/java/io/appium/espressoserver/lib/model/Element.java
- test/functional/commands/find-e2e-specs.js
- test/functional/desired.js
Espresso tests were flakey, and I suspect that the issue was that when retrieving cached Views (via `Element.getViewById(id)`, it wasn't waiting for the main thread to be idle and there was race conditions where it was finding `Views` that still were in the view hierarchy that were about to not be there.
Example:
```javascript
it('should throw a stale element exception if clicking on element that does not exist', async function () {
let el = await driver.elementByXPath("//*[@content-desc='Animation']");
await el.click();
await el.click().should.eventually.be.rejectedWith(/no longer exists /);
await driver.back();
});
```
On the second call to `el.click()`, the element was still in the view hierarchy, because it didn't jump to the new activity yet. So what was happening is that it finds …
> Make getViewById wait for main thread idle

- espresso-server/app/src/androidTest/java/io/appium/espressoserver/lib/handlers/MobileSwipe.java
- espresso-server/app/src/androidTest/java/io/appium/espressoserver/lib/helpers/w3c/adapter/DummyW3CActionAdapter.java
- espresso-server/app/src/androidTest/java/io/appium/espressoserver/lib/helpers/w3c/adapter/W3CActionAdapter.java
- espresso-server/app/src/androidTest/java/io/appium/espressoserver/lib/helpers/w3c/adapter/espresso/EspressoW3CActionAdapter.java
- espresso-server/app/src/androidTest/java/io/appium/espressoserver/lib/http/Router.java
- espresso-server/app/src/androidTest/java/io/appium/espressoserver/lib/model/Element.java
- package.json
- test/functional/commands/find-e2e-specs.js
* Views that are part of an AdapterView don't always have the same data (`value`, `contentDescription`, etc...) throughout their lifecycle. This is because AdapterView stores data about elements in memory and only render views that are on-screen. When views get scrolled away from, instead of re-creating new views, views are re-cycled with updated `contentDescription`, `text`, etc... (see https://stackoverflow.com/questions/11945563/how-listviews-recycling-mechanism-works for reference)
* This will cause unexpected element caching results. If you locate a view, `el`, that is inside a ListView, and then the  ListView is scrolled, for instance, the Views will have their data "re-shuffled" and `el` will have different data.
* For the most part, we can't do anything about this because we cache …
> Scroll elements back into view when scrolled out

- espresso-server/app/src/androidTest/java/io/appium/espressoserver/lib/handlers/exceptions/MoveTargetOutOfBoundsException.java
- espresso-server/app/src/androidTest/java/io/appium/espressoserver/lib/helpers/AndroidLogger.java
- espresso-server/app/src/androidTest/java/io/appium/espressoserver/lib/helpers/Logger.java
- espresso-server/app/src/androidTest/java/io/appium/espressoserver/lib/helpers/w3c/adapter/BaseW3CActionAdapter.java
- espresso-server/app/src/androidTest/java/io/appium/espressoserver/lib/helpers/w3c/adapter/DummyW3CActionAdapter.java
- espresso-server/app/src/androidTest/java/io/appium/espressoserver/lib/helpers/w3c/adapter/W3CActionAdapter.java
- espresso-server/app/src/androidTest/java/io/appium/espressoserver/lib/helpers/w3c/adapter/espresso/EspressoW3CActionAdapter.java
- espresso-server/app/src/androidTest/java/io/appium/espressoserver/lib/helpers/w3c/dispatcher/DispatchPointerMoveResult.java
- espresso-server/app/src/androidTest/java/io/appium/espressoserver/lib/helpers/w3c/dispatcher/KeyDispatch.java
- espresso-server/app/src/androidTest/java/io/appium/espressoserver/lib/helpers/w3c/dispatcher/PointerDispatch.java
- espresso-server/app/src/androidTest/java/io/appium/espressoserver/lib/helpers/w3c/models/ActionObject.java
- espresso-server/app/src/androidTest/java/io/appium/espressoserver/lib/helpers/w3c/models/ActionSequence.java
- espresso-server/app/src/androidTest/java/io/appium/espressoserver/lib/helpers/w3c/models/InputSource.java
- espresso-server/app/src/androidTest/java/io/appium/espressoserver/lib/helpers/w3c/models/Tick.java
- espresso-server/app/src/androidTest/java/io/appium/espressoserver/lib/helpers/w3c/processor/PauseProcessor.java
- espresso-server/app/src/androidTest/java/io/appium/espressoserver/lib/helpers/w3c/processor/PointerProcessor.java
- espresso-server/app/src/androidTest/java/io/appium/espressoserver/lib/helpers/w3c/processor/ProcessorHelpers.java
- espresso-server/app/src/androidTest/java/io/appium/espressoserver/lib/helpers/w3c/state/PointerInputState.java
- espresso-server/app/src/test/java/io/appium/espressoserver/test/helpers/w3c/ActionSequenceTest.java
- espresso-server/app/src/test/java/io/appium/espressoserver/test/helpers/w3c/ActionsTest.java
- espresso-server/app/src/test/java/io/appium/espressoserver/test/helpers/w3c/InputSourceTest.java
- espresso-server/app/src/test/java/io/appium/espressoserver/test/helpers/w3c/PointerDispatchTest.java
- espresso-server/app/src/test/java/io/appium/espressoserver/test/helpers/w3c/ProcessorTest.java
- espresso-server/app/src/test/java/io/appium/espressoserver/test/helpers/w3c/TickTest.java
- espresso-server/app/src/test/java/io/appium/espressoserver/test/model/TouchActionTest.java
* Use floats as type for `x`, `y` and `duration` so that it doesn't break when a float is provided in Actions JSON
* When floats are provided in Actions JSON, round the values and provide warning to user if rounded value is different from provided value
* Also, add 'warn' as a log type (along with 'info', 'debug' and 'error')
> Make "Actions" accept floats for "x", "y" and "duration" properties

- espresso-server/app/src/androidTest/java/io/appium/espressoserver/lib/handlers/GetToastVisibility.java
- espresso-server/app/src/androidTest/java/io/appium/espressoserver/lib/http/Router.java
- espresso-server/app/src/androidTest/java/io/appium/espressoserver/lib/model/ToastLookupParams.java
- espresso-server/app/src/androidTest/java/io/appium/espressoserver/lib/viewmatcher/RegexpTextMatcher.java
- espresso-server/app/src/androidTest/java/io/appium/espressoserver/lib/viewmatcher/ToastMatcher.java
- lib/commands/execute.js
- lib/commands/general.js
`mobile: isToastVisible`
Arguments:
`text` - mandatory argument. Either exact toast text or a regular expression (depending on `isRegexp ` value)
`isRegexp` - optional argument. If set to `true` then `text` will be parsed as regular expression pattern. By default the matching by exact toast text is performed.
> Add mobile: endpoint to verify toast messages presence

- espresso-server/app/src/androidTest/java/io/appium/espressoserver/lib/model/ViewElement.java
Now we return an empty string for missing resource ids, which clutters the output XML page source
> Return null if resource id is unset

- espresso-server/app/src/androidTest/java/io/appium/espressoserver/lib/handlers/DrawerActionHandler.java
- espresso-server/app/src/androidTest/java/io/appium/espressoserver/lib/handlers/NavigateTo.java
- espresso-server/app/src/androidTest/java/io/appium/espressoserver/lib/handlers/ScreenshotHandler.java
- espresso-server/app/src/androidTest/java/io/appium/espressoserver/lib/handlers/ScrollToPage.java
- espresso-server/app/src/androidTest/java/io/appium/espressoserver/lib/handlers/SetDate.java
- espresso-server/app/src/androidTest/java/io/appium/espressoserver/lib/handlers/SetTime.java
- espresso-server/app/src/androidTest/java/io/appium/espressoserver/lib/http/Router.java
- espresso-server/app/src/androidTest/java/io/appium/espressoserver/lib/model/DrawerActionParams.java
- espresso-server/app/src/androidTest/java/io/appium/espressoserver/lib/model/NavigateToParams.java
- espresso-server/app/src/androidTest/java/io/appium/espressoserver/lib/model/ScrollToPageParams.java
- espresso-server/app/src/androidTest/java/io/appium/espressoserver/lib/model/SetDateParams.java
- espresso-server/app/src/androidTest/java/io/appium/espressoserver/lib/model/SetTimeParams.java
- lib/commands/execute.js
- lib/commands/general.js
- package.json
- test/functional/commands/mobile-e2e-specs.js
Mobile commands: `setDate`, `setTime`, `navigateTo`, `scrollToPage`, `openDrawer`, `closeDrawer`
(connect with: https://github.com/appium/appium-espresso-driver/issues/323)
> Implement Espresso contrib mobile commands

- espresso-server/app/src/androidTest/java/io/appium/espressoserver/lib/http/Router.java
- espresso-server/app/src/androidTest/java/io/appium/espressoserver/lib/http/Server.java
Also adds proper error description in case the application under test does not declare internet permission in its manifest.
> Update deprecated routing methods

- lib/driver.js
`pushSettingsApp` was called twice in a row, since initDevice also contains this call. See https://gist.github.com/cosminstirbu/8f9e3b8c542b49e93626e31b9148cf58 for more details.
@KazuCocoa FYI
> Make sure the settings helper is only installed once

- espresso-server/app/src/androidTest/java/io/appium/espressoserver/lib/handlers/MobileViewFlash.java
- espresso-server/app/src/androidTest/java/io/appium/espressoserver/lib/http/Router.java
- espresso-server/app/src/androidTest/java/io/appium/espressoserver/lib/model/ViewFlashParams.java
- lib/commands/execute.js
- lib/commands/general.js
Flash the element on the screen. This helps to ensure if we are finding right element
> Add endpoint to flash element on screen

- espresso-server/app/src/androidTest/java/io/appium/espressoserver/lib/model/SourceDocument.java
- espresso-server/app/src/androidTest/java/io/appium/espressoserver/lib/viewmatcher/WithXPath.java
Another try to address https://github.com/appium/appium-espresso-driver/issues/340
> Stream xml to a file rather than to a memory

- espresso-server/app/src/androidTest/java/io/appium/espressoserver/lib/handlers/GetEnabled.java
- espresso-server/app/src/androidTest/java/io/appium/espressoserver/lib/handlers/GetSelected.java
Espresso server crashes on calling `/enabled` or `/selected` 
```
--------- beginning of crash
12-14 16:23:31.349 16968 17441 E AndroidRuntime: FATAL EXCEPTION: NanoHttpd Request Processor (#33)
12-14 16:23:31.349 16968 17441 E AndroidRuntime: Process: com.bumble.app, PID: 16968
12-14 16:23:31.349 16968 17441 E AndroidRuntime: androidx.test.espresso.base.DefaultFailureHandler$AssertionFailedWithCauseError: 'is enabled' doesn't match the selected view.
12-14 16:23:31.349 16968 17441 E AndroidRuntime: Expected: is enabled
12-14 16:23:31.349 16968 17441 E AndroidRuntime:      Got: "LoadingButton{id=2131363209, res-name=registration_continue, visibility=VISIBLE, width=468, height=90, has-focus=false, has-focusable=true, has-window-focus=true, is-clickable=false, is-enabled=false, …
```
> Fix crash on /enabled and /selected

- .travis.yml
- espresso-server/app/build.gradle
- espresso-server/app/src/androidTest/java/io/appium/espressoserver/EspressoServerRunnerTest.java
- espresso-server/app/src/androidTest/java/io/appium/espressoserver/lib/model/SourceDocument.java
- espresso-server/app/src/test/java/io/appium/espressoserver/test/model/SourceDocumentTest.java
- package.json
* Add a test that would cause a Java heap error, if not for the XML traversal depth limit introduced by: https://github.com/appium/appium-espresso-driver/pull/341
* Runs the tests on Travis CI now. Skips the Espresso Server test by adding a property that tells the test to be skipped.
> Test source document

- lib/espresso-runner.js
- test/unit/espresso-runner-specs.js
Alternative of https://github.com/appium/appium-espresso-driver/pull/357
- Uninstall if installed espresso server is older or newer than new espresso server
- Install new espresso server if uninstall happened or not installed it
- ~~Make sure the installation by checking `io.appium.espressoserver.test/androidx.test.runner.AndroidJUnitRunner`~~ <= early optimisation 
- Current master has been updated to `androidx`
> Uninstall if installed version is older or newer than new one

- test/unit/driver-specs.js
The unit test failed when an Android Device wasn't launch. Created a stub for this method to allow tests to be run without an Android device.
> Stub getDeviceInfoForCaps

- lib/driver.js
- test/unit/driver-specs.js
Just today, I noticed Espresso driver had no `nativeWebScreenshot`. We cannot get screenshot in webview context. uiautomator2 also cannot get screenshot in webview if `nativeWebScreenshot` is not enabled.
(I will add test code later.)
----
- Error when I tried to get screenshot in webview context
```
[HTTP] --> GET /wd/hub/session/1a3fc9a9-0684-40b4-9add-32a416e728e6/screenshot
[HTTP] {}
[W3C (1a3fc9a9)] Driver proxy active, passing request on via HTTP proxy
[debug] [WD Proxy] Matched '/wd/hub/session/1a3fc9a9-0684-40b4-9add-32a416e728e6/screenshot' to command name 'getScreenshot'
[debug] [WD Proxy] Proxying [GET /wd/hub/session/1a3fc9a9-0684-40b4-9add-32a416e728e6/screenshot] to [GET http://127.0.0.1:8000/wd/hub/session/1564e8c3fe4d676d33410f6d2c5d0e3f/screenshot] with body: {}
[WD …
```
> add nativeWebScreenshot

- lib/commands/execute.js
`clickAction` was missing from the mobile command mapping.
> [fix the build] Add clickAction to mobile mapping

- espresso-server/app/src/androidTest/java/io/appium/espressoserver/lib/handlers/SetOrientation.java
The elementId parameter is not specified in the Set Orientation definition:
http://appium.io/docs/en/commands/session/orientation/set-orientation/
Since the SetOrientation handler in espresso server requires an elementId parameter, the java-client's device.rotate(ScreeOrientation.LANDSCAPE) method produces errors like this...
org.openqa.selenium.WebDriverException: An unknown server-side error occurred while processing the command. Original error: java.lang.NullPointerException: Attempt to invoke virtual method 'int java.lang.Object.hashCode()' on a null object reference
at java.util.concurrent.ConcurrentHashMap.get(ConcurrentHashMap.java:915)
at java.util.concurrent.ConcurrentHashMap.containsKey(ConcurrentHashMap.java:943)
at io.appium.espressoserver.lib.model.Element.exists(Element.java: …
> Handle no elementId

- lib/driver.js
- lib/espresso-runner.js
- package.json
appium/appium-android-driver#502 for espresso driver.
This feature helps users to remove unnecessary apps before their tests.
https://github.com/appium/appium/pull/12278
> add uninstallOtherPackages for espresso driver

- espresso-server/app/src/androidTest/java/io/appium/espressoserver/lib/http/Router.java
I observe some mess with these endpoints in different clients, so it would be safer to have aliases for all possible options
> Add aliases to alert endpoints

- espresso-server/app/src/androidTest/java/io/appium/espressoserver/lib/handlers/CreateSession.kt
- espresso-server/app/src/androidTest/java/io/appium/espressoserver/lib/handlers/StartActivity.kt
- espresso-server/app/src/androidTest/java/io/appium/espressoserver/lib/helpers/ActivityHelper.java
- espresso-server/app/src/androidTest/java/io/appium/espressoserver/lib/model/SessionParams.kt
- espresso-server/app/src/androidTest/java/io/appium/espressoserver/lib/model/StartActivityParams.kt
- espresso-server/app/src/test/java/io/appium/espressoserver/test/helpers/KReflectionUtilsTest.kt
- espresso-server/build.gradle
- lib/commands/general.js
- lib/driver.js
- test/functional/commands/mobile-e2e-specs.js
- test/functional/commands/touch-e2e-specs.js
- test/functional/driver-e2e-specs.js
- test/functional/webview/web-e2e-specs.js
- test/unit/driver-specs.js
Addresses https://github.com/appium/appium/issues/12414
ADB is better in detecting activities than pure instrumentation methods
> Use ADB helpers to wait for activities

- espresso-server/app/src/androidTest/java/io/appium/espressoserver/lib/handlers/CreateSession.kt
- espresso-server/app/src/androidTest/java/io/appium/espressoserver/lib/handlers/StartActivity.kt
- espresso-server/app/src/androidTest/java/io/appium/espressoserver/lib/helpers/ActivityHelper.java
- espresso-server/app/src/androidTest/java/io/appium/espressoserver/lib/model/SessionParams.kt
- espresso-server/app/src/androidTest/java/io/appium/espressoserver/lib/model/StartActivityParams.kt
- espresso-server/app/src/test/java/io/appium/espressoserver/test/helpers/KReflectionUtilsTest.kt
- espresso-server/build.gradle
- espresso-server/gradle/wrapper/gradle-wrapper.properties
- lib/commands/general.js
- lib/driver.js
- lib/utils.js
Hopefully addresses https://github.com/appium/appium-espresso-driver/issues/439
> Tune activities startup

- espresso-server/app/src/androidTest/java/io/appium/espressoserver/lib/model/AppiumParams.kt
- lib/commands/general.js
- test/functional/commands/mobile-e2e-specs.js
closes https://github.com/appium/appium-espresso-driver/issues/453
`targetElement`  is used by Gson in MobileBackdoorParams to map a parameter instead of `elementId` after https://github.com/appium/appium-espresso-driver/pull/405
> fix element id in mobile backdoor

- espresso-server/app/src/androidTest/java/io/appium/espressoserver/lib/handlers/GetDeviceInfo.kt
- espresso-server/app/src/androidTest/java/io/appium/espressoserver/lib/helpers/DeviceInfoHelper.kt
Added timezone and locale as same as https://github.com/appium/appium-xcuitest-driver/pull/1003
```
@driver.execute_script 'mobile: deviceInfo', {}
=> {"realDisplaySize"=>"1080x1920",
"apiVersion"=>"28",
"carrierName"=>"Android",
"platformVersion"=>"9",
"timeZone"=>"Asia/Tokyo",
"model"=>"Android SDK built for x86_64",
"locale"=>"ja_JP",
"brand"=>"google",
"androidId"=>"918a8c16d0e7c7ec",
"manufacturer"=>"Google",
"displayDensity"=>420}
```
> Add tiemzone and locale in deviceinfo

- espresso-server/app/src/androidTest/java/io/appium/espressoserver/lib/handlers/SendKeys.kt
- test/functional/commands/keyboard-e2e-specs.js
From Appium 1.12.0,  sending multibyte string has failed by _send key_ because the control flow was opposit
(worked till 1.11)
> fix: send key multi byte string

- espresso-server/app/src/androidTest/java/io/appium/espressoserver/lib/handlers/GetOrientation.kt
- espresso-server/app/src/androidTest/java/io/appium/espressoserver/lib/handlers/SetOrientation.kt
- espresso-server/app/src/androidTest/java/io/appium/espressoserver/lib/model/OrientationType.kt
- test/functional/commands/orientation-e2e-specs.js
Fixes https://github.com/appium/appium-espresso-driver/issues/479
I noticed current get orientation did not work since it returned error or int value instead of 'LANDSCAPE' or 'PORTRAIT' strings
----
I've tested with Ruby code on my local, for now.
> fix set/get orientation

- espresso-server/app/src/androidTest/java/io/appium/espressoserver/lib/handlers/GetClipboard.kt
- espresso-server/app/src/androidTest/java/io/appium/espressoserver/lib/handlers/SetClipboard.kt
- espresso-server/app/src/androidTest/java/io/appium/espressoserver/lib/model/ClipboardDataType.kt
- espresso-server/app/src/androidTest/java/io/appium/espressoserver/lib/model/GetClipboardParams.kt
- espresso-server/app/src/androidTest/java/io/appium/espressoserver/lib/model/SetClipboardParams.kt
- test/functional/commands/clipboard-e2e-specs.js
Below error happens against `[debug] [WD Proxy] Proxying [POST /wd/hub/session/50c33b86-8579-4d8a-911b-b175996978b6/appium/device/set_clipboard] to [POST http://localhost:8200/session/24fe3836-7a6c-4a01-a57c-be0c4a6e327e/appium/device/set_clipboard] with body: {"contentType":"plaintext","content":"aGFwcHkgdGVzdGluZw==","label":"Note"}` since the contentType was lower case. Not sure from when, but recent espresso driver can work for `PLAINTEXT` case even if previosly it accepts `plaintext`.
```
Selenium::WebDriver::Error::InvalidArgumentError: io.appium.espressoserver.lib.handlers.exceptions.InvalidArgumentException: java.lang.IllegalArgumentException: Parameter specified as non-null is null: method kotlin.jvm.internal.Intrinsics.checkParameterIsNotNull, parameter contentType
at …
```
> fix: clipboard get/set contentType

- ci-jobs/pr-validation.yml
- lib/driver.js
- test/functional/commands/contexts-e2e-specs.js
closes https://github.com/appium/appium-espresso-driver/issues/482
Espresso driver has no default curContext, so switch context does not work expectedly.
Will add an e2e test case later.
I've already tested on my local in Ruby.
> fix: store curContext in createSession

- espresso-server/app/src/androidTest/java/io/appium/espressoserver/lib/handlers/ElementValue.kt
- espresso-server/app/src/androidTest/java/io/appium/espressoserver/lib/model/ElementValueParams.kt
- test/functional/commands/element-values-e2e-specs.js
- test/functional/commands/keyboard-e2e-specs.js
Below error happens for set immediate value and replace value.
```
Selenium::WebDriver::Error::InvalidArgumentError:         Selenium::WebDriver::Error::InvalidArgumentError: com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected a string but was BEGIN_ARRAY at line 1 column 11 path $.value
io.appium.espressoserver.lib.handlers.exceptions.InvalidArgumentException: com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected a string but was BEGIN_ARRAY at line 1 column 11 path $.value
at io.appium.espressoserver.lib.http.Router.route(Router.kt:203)
at io.appium.espressoserver.lib.http.Server.serve(Server.kt:49)
at fi.iki.elonen.NanoHTTPD$HTTPSession.execute(NanoHTTPD.java:945)
at fi.iki.elonen.NanoHTTPD$ClientHandler.run(NanoHTTPD.java:192)
at …
```
> fix set value immediately, replace value

- espresso-server/app/src/androidTest/java/io/appium/espressoserver/lib/helpers/w3c/adapter/DummyW3CActionAdapter.kt
- espresso-server/app/src/androidTest/java/io/appium/espressoserver/lib/helpers/w3c/adapter/espresso/EspressoW3CActionAdapter.kt
- espresso-server/app/src/androidTest/java/io/appium/espressoserver/lib/http/response/AppiumResponse.kt
- espresso-server/app/src/test/java/io/appium/espressoserver/test/helpers/w3c/ActionSequenceTest.kt
- espresso-server/app/src/test/java/io/appium/espressoserver/test/helpers/w3c/PointerDispatchTest.kt
- espresso-server/app/src/test/java/io/appium/espressoserver/test/helpers/w3c/ProcessorTest.kt
- espresso-server/app/src/test/java/io/appium/espressoserver/test/helpers/w3c/TickTest.kt
This simplifies parsing of debug logs
> Always print the original stacktrace rather than the wrapped one

- lib/commands/general.js
Current `launchApp` missed espresso session like below scenario since espresso-driver does not establish a new session with the launched app
```
@driver.close_app
assert(@@core.wait { @driver.app_state('io.appium.android.apis') != :running_in_foreground })
@driver.launch_app
e = @@core.wait { @driver.find_element :accessibility_id, 'App' }
assert_equal 'App', e.text
```
Then, below error raises in `find_element`.
```
Appium::Core::Wait::TimeoutError: timed out after 20 seconds (An unknown server-side error occurred while processing the command. Original error: Could not proxy. Proxy error: Could not proxy command to remote server. Original error: Error: socket hang up)
```
https://dev.azure.com/kazucocoa/ruby_lib_core/_build/results?buildId=1265
> fix raise an error for launch app and close app since they do not need in espresso

- espresso-server/app/src/androidTest/java/io/appium/espressoserver/lib/handlers/CreateSession.kt
- espresso-server/app/src/androidTest/java/io/appium/espressoserver/lib/handlers/GetSession.kt
- espresso-server/app/src/androidTest/java/io/appium/espressoserver/lib/handlers/GetSessions.kt
- espresso-server/app/src/androidTest/java/io/appium/espressoserver/lib/handlers/exceptions/SessionNotCreatedException.kt
- espresso-server/app/src/androidTest/java/io/appium/espressoserver/lib/http/Router.kt
- espresso-server/app/src/androidTest/java/io/appium/espressoserver/lib/model/Session.kt
- espresso-server/app/src/androidTest/java/io/appium/espressoserver/lib/model/SessionParams.kt
- lib/espresso-runner.js
I've totally missed the fact that firstMatch/alwaysMatch should be under 'capabilities' key
> fix: Sync createSession parameters with W3C spec

- lib/commands/general.js
https://github.com/appium/appium-espresso-driver/pull/485 for `reset`
Reset also close/launch the app.
For espresso, delete/create session are the same meaning.
closes https://github.com/appium/appium-espresso-driver/issues/459
> fix: raise an error for reset as same as launchApp and closeApp

- README.md
- lib/driver.js
(I inserted `new Error()` in create session)
- server
```
[debug] [Espresso] Deleting espresso session
[Espresso] Unable to remove port forward 'Cannot read property 'removePortForward' of undefined'
[debug] [BaseDriver] Event 'newSessionStarted' logged at 1570106294202 (21:38:14 GMT+0900 (Japan Standard Time))
[debug] [W3C] Encountered internal error running command: Error: Error!!!!. If the reason might be espresso driver or server, please read troubleshooting https://github.com/appium/appium-espresso-driver#contributing
[debug] [W3C]     at EspressoDriver.Error [as createSession] (/Users/kazu/GitHub/appium-espresso-driver/lib/driver.js:171:13)
[HTTP] <-- POST /wd/hub/session 500 9 ms - 779
[HTTP]
```
- client
```
Selenium::WebDriver::Error::SessionNotCreatedError: …
```
> feat: add link to troubleshooting to guide users to the troubleshooting

- lib/commands/general.js
- lib/driver.js
- package.json
The part of https://github.com/appium/appium/issues/13466 implementation
> feat: Update clipboard retrieval for Android 10+

- lib/desired-caps.js
- lib/driver.js
Rebuilding the espresso-server using Gradle is time-consuming on slower machines and increases startup time significantly. With uiautomator2-driver there is a capability called `skipServerInstallation` which assumes that the device already has required servers. This can be usable with espresso-driver
> use skipServerInstallation same way as with uiautomator2-driver

- lib/espresso-runner.js
Device udid is supposed to be always unique (we cannot start two sessions on the same device at the same time). This fix then guarantees there will be no conflicts if parallel tests are being executed on different devices for the same app version.
> fix: Add device udid to the server folder root

- lib/espresso-runner.js
It seems like `adb.udid` is not actually used, although `curDeviceId` is used instead
> fix: Use appropriate adb property

- espresso-server/app/src/androidTest/java/io/appium/espressoserver/lib/viewmatcher/ToastMatcher.kt
I found a regression
https://dev.azure.com/kazucocoa/ruby_lib_core/_build/results?buildId=1733&view=logs&j=cf3f09f0-b33f-5a9c-9a54-00702f010006&t=0c6beea2-cf53-5c48-3d66-9fd06ae199bb
Espresso driver failed to find a toast message after tapping 'pot toast' below.
`TYPE_TOAST` has a deprecated mark, so it was replaced with `TYPE_APPLICATION_OVERLAY`, but it caused the regression.
Espresso driver's build environment could depend on a user environment, so I think it is safe to check the running environment has `TYPE_TOAST`. It makes performance slightly slow, but on my local test, the slowness should not be an issue since this effect only for toast.
> fix a toast regression

- ci-jobs/ci.yml
- ci-jobs/nightly.yml
- ci-jobs/pr-validation.yml
- ci-jobs/scripts/start-emulator.sh
- espresso-server/app/src/androidTest/java/io/appium/espressoserver/lib/helpers/w3c/adapter/espresso/AndroidKeyEvent.kt
- espresso-server/app/src/androidTest/java/io/appium/espressoserver/lib/helpers/w3c/dispatcher/KeyDispatch.kt
- espresso-server/app/src/test/java/io/appium/espressoserver/test/model/TouchActionTest.kt
- test/functional/desired.js
Java11 does not like that Mockito is trying to replace static methods, so I've just removed that verification from tests:
```
npm ERR! io.appium.espressoserver.test.model.TouchActionTest > shouldConvertPress FAILED
npm ERR!     org.mockito.exceptions.base.MockitoException at TouchActionTest.kt:28
npm ERR!         Caused by: java.lang.UnsupportedOperationException at TouchActionTest.kt:28
npm ERR!             Caused by: java.lang.IllegalArgumentException at TouchActionTest.kt:28
npm ERR! 
npm ERR! io.appium.espressoserver.test.model.TouchActionTest > shouldConvertMoveTo FAILED
npm ERR!     org.mockito.exceptions.base.MockitoException at TouchActionTest.kt:28
npm ERR!         Caused by: java.lang.UnsupportedOperationException at TouchActionTest.kt:28
npm ERR!             Caused by: …
```
> chore: Make the source compilable using java11

- espresso-server/app/src/androidTest/java/io/appium/espressoserver/lib/handlers/StartService.kt
- espresso-server/app/src/androidTest/java/io/appium/espressoserver/lib/handlers/StopService.kt
- espresso-server/app/src/androidTest/java/io/appium/espressoserver/lib/helpers/IntentHelpers.kt
- espresso-server/app/src/androidTest/java/io/appium/espressoserver/lib/http/Router.kt
- espresso-server/app/src/androidTest/java/io/appium/espressoserver/lib/model/StartServiceParams.kt
- espresso-server/app/src/androidTest/java/io/appium/espressoserver/lib/model/StopServiceParams.kt
- lib/commands/execute.js
- lib/commands/services.js
- package.json
Espresso is limited to app sandbox, so there is no point to have this endpoint calling `adb shell am` like in UIA2. It works with `InstrumentationRegistry.getInstrumentation().targetContext` entity instead and only accepts services that are implemented in scope of the current app under test.
> feat: Add startService/stopService mobile helpers

- espresso-server/app/src/androidTest/java/io/appium/espressoserver/lib/helpers/ThreadHelpers.kt
- espresso-server/app/src/androidTest/java/io/appium/espressoserver/lib/helpers/ViewFinder.kt
Sometimes, the find_elements take 60 seconds and returns empty results. 
This is because app is not idle and we swallow this exception and wait for 60 seconds of a timeout to finish
We must not swallow this AppNotIdleException
> chore: Catch only NoMatchingViewException, do not swallow AppNotIdleException

- lib/driver.js
- lib/espresso-runner.js
https://github.com/appium/appium-espresso-driver/issues/590
> feat: Throw InvalidContextError if instrumentation process crashes unexpectedly

- espresso-server/app/build.gradle
This PR takes forward work started by @tinder-ktarasov in his PR #497, hoping that this will fix issues in #449.
Initial submission had some failing tests (but logs are no longer accessible). 
In a short setting "transitive = false" stops gradle from loading espresso-contrib's dependendencies. However, adding it fails one of the tests with some "Navigation" class missing. After adding "com.google.android.material:material:1.2.0" this test no longer failed.
Note that android.material package is in espresson-contrib dependencies, so in fact we're removing all but one of dependent packages from build.
I'm not sure if that's the right "gradle" solution. I'm open for a discussion.
> fix: Exclude transitive dependencies of espresso-contrib

- espresso-server/app/src/androidTest/java/io/appium/espressoserver/lib/handlers/ListIdlingResources.kt
- espresso-server/app/src/androidTest/java/io/appium/espressoserver/lib/handlers/MobileBackdoor.kt
- espresso-server/app/src/androidTest/java/io/appium/espressoserver/lib/handlers/RegisterIdlingResources.kt
- espresso-server/app/src/androidTest/java/io/appium/espressoserver/lib/handlers/UnregisterIdlingResources.kt
- espresso-server/app/src/androidTest/java/io/appium/espressoserver/lib/http/Router.kt
- espresso-server/app/src/androidTest/java/io/appium/espressoserver/lib/model/IdlingResourcesParams.kt
- espresso-server/build.gradle
- lib/commands/execute.js
- lib/commands/idling-resources.js
- lib/commands/index.js
- lib/commands/services.js
- lib/utils.js
The concept itself requires to change the app under test, but I assume the feature itself could be quite useful for people that know what they are doing.
> feat: Add support for idling resources

- lib/espresso-runner.js
- test/functional/driver-e2e-specs.js
- test/functional/helpers/session.js
It looks like on some device the instrumentation process keeps silence, so it makes sense to detect the server startup using the fact it starts responding to `/status` requests like we do in UIA2. Also, added more visibility and perf starts to the server startup process.
> refactor: Improve the server startup logic

- espresso-server/app/src/androidTest/java/io/appium/espressoserver/lib/handlers/ListIdlingResources.kt
- espresso-server/app/src/androidTest/java/io/appium/espressoserver/lib/helpers/ClipboardHelper.kt
- espresso-server/app/src/androidTest/java/io/appium/espressoserver/lib/helpers/LocaleHelpers.kt
In order to test our application, we need to build the espresso test app with Target SDK version 29.
To do so, I've addressed several minor changes.
> refactor: Allow target SDK 29

- espresso-server/app/src/androidTest/java/io/appium/espressoserver/lib/helpers/InvocationOperation.java
Some Backdoors got broken recently because getDeclaredMethod finds only methods of current class. changing back to getMethod to fix the issue
> Fix looking up for methods in parent classes

- espresso-server/app/src/androidTest/java/io/appium/espressoserver/lib/handlers/UiautomatorPageSource.kt
- espresso-server/app/src/androidTest/java/io/appium/espressoserver/lib/http/Router.kt
- lib/commands/execute.js
- lib/commands/general.js
Problem: `driver.page_source` doesn't return page source when AUT is not in focus.
We had an issue while working on an application flow where the test navigates outside of the AUT's context. The test performs a photo upload operation as part of the test flow. When the active app is not AUT we use `driver.execute_script('mobile:uiautomator',*args)` to perform the UI interactions. 
When a test fails our framework attaches the screenshot and page source of the active screen. But when the active app is not AUT, espresso driver can't return the page source with `driver.page_source`. To overcome this we can dump the UI dom with UIDevice.
Problem with the current implementation:
1. UI dump returned by this PR's change is not ready to be consumed by the Appium Inspector.
2. I'm unsure whether …
> feat: Add mobile endpoint to retrieve UIAutomator page source dump

- lib/driver.js
- lib/espresso-runner.js
It makes sense to check if the server is alive before we sending any request to it. `executeCommand` might also fail even if the proxy is pointing to a web view, which is not the behaviour we want.
> refactor: Move Espresso server state check into the corresponding proxy

- espresso-server/app/src/androidTest/java/io/appium/espressoserver/lib/model/SourceDocument.kt
- espresso-server/app/src/androidTest/java/io/appium/espressoserver/lib/viewmatcher/WithXPath.kt
- espresso-server/app/src/test/java/io/appium/espressoserver/test/helpers/XpathQueryParserTests.kt
Querying view attributes is expensive and takes time. Although xpath lookup only requires some attributes to be there and does not need them all
> feat: Speed up xpath lookup by only including the requested attributes

- lib/commands/general.js
- test/functional/driver-e2e-specs.js
Closes https://github.com/appium/appium-espresso-driver/issues/648
We originally expected this method raised an error. So this PR keeps it.
> fix: raise an error for reset

- espresso-server/settings.gradle
- espresso-server/settings.gradle.kts
- lib/server-builder.js
- test/unit/server-builder-specs.js
https://github.com/appium/appium-espresso-driver/issues/664 failed because of no proper command on the Azure host.
Potentially we should add `app:`  for some environment.
Let me try this change out.
(My local env had no issue with/without `app:`)
> chore: tweak assembleAndroidTest command

- lib/espresso-runner.js
https://github.com/appium/appium-uiautomator2-driver/pull/452 for espresso
> feat: add disableAnalytics true

- espresso-server/app/src/androidTest/java/io/appium/espressoserver/lib/handlers/CreateSession.kt
- espresso-server/app/src/androidTest/java/io/appium/espressoserver/lib/handlers/GetSessions.kt
- espresso-server/app/src/androidTest/java/io/appium/espressoserver/lib/handlers/GetWindowSize.kt
- espresso-server/app/src/androidTest/java/io/appium/espressoserver/lib/handlers/NoSessionCommandHandler.kt
- espresso-server/app/src/androidTest/java/io/appium/espressoserver/lib/handlers/NotYetImplemented.kt
- espresso-server/app/src/androidTest/java/io/appium/espressoserver/lib/handlers/RequestHandler.kt
- espresso-server/app/src/androidTest/java/io/appium/espressoserver/lib/handlers/SetClipboard.kt
- espresso-server/app/src/androidTest/java/io/appium/espressoserver/lib/handlers/SetDate.kt
- espresso-server/app/src/androidTest/java/io/appium/espressoserver/lib/handlers/SetOrientation.kt
- espresso-server/app/src/androidTest/java/io/appium/espressoserver/lib/handlers/SetTime.kt
- espresso-server/app/src/androidTest/java/io/appium/espressoserver/lib/handlers/StartService.kt
- espresso-server/app/src/androidTest/java/io/appium/espressoserver/lib/handlers/Status.kt
- espresso-server/app/src/androidTest/java/io/appium/espressoserver/lib/handlers/StopService.kt
- espresso-server/app/src/androidTest/java/io/appium/espressoserver/lib/handlers/Text.kt
Currently there is no such validation, which means one could execute session command with basically any provided id
> fix: Add session identifier verification

- README.md
Probably adding a link to keystore is better than nothing who does not know about keystore.
> docs: add a link to signing in readme

- ci-jobs/templates/android-e2e-template.yml
- espresso-server/app/build.gradle.kts
- espresso-server/app/src/androidTest/java/io/appium/espressoserver/lib/drivers/ComposeDriver.kt
- espresso-server/app/src/androidTest/java/io/appium/espressoserver/lib/handlers/GetDeviceInfo.kt
- espresso-server/app/src/androidTest/java/io/appium/espressoserver/lib/handlers/GetWindowRect.kt
- espresso-server/app/src/androidTest/java/io/appium/espressoserver/lib/handlers/GetWindowSize.kt
- espresso-server/app/src/androidTest/java/io/appium/espressoserver/lib/handlers/SetOrientation.kt
- espresso-server/app/src/androidTest/java/io/appium/espressoserver/lib/handlers/UpdateSettings.kt
- espresso-server/app/src/androidTest/java/io/appium/espressoserver/lib/helpers/AlertHelpers.kt
- espresso-server/app/src/androidTest/java/io/appium/espressoserver/lib/helpers/DeviceInfoHelper.kt
- espresso-server/app/src/androidTest/java/io/appium/espressoserver/lib/helpers/GsonParserHelpers.kt
- espresso-server/app/src/androidTest/java/io/appium/espressoserver/lib/helpers/IMEHelpers.kt
- espresso-server/app/src/androidTest/java/io/appium/espressoserver/lib/helpers/IntentHelpers.kt
- espresso-server/app/src/androidTest/java/io/appium/espressoserver/lib/helpers/SizeHelpers.kt
- espresso-server/app/src/androidTest/java/io/appium/espressoserver/lib/helpers/w3c/caps/CapsUtils.kt
- espresso-server/app/src/androidTest/java/io/appium/espressoserver/lib/model/ClipboardDataType.kt
- espresso-server/app/src/androidTest/java/io/appium/espressoserver/lib/model/ViewAttributesEnum.kt
- espresso-server/app/src/androidTest/java/io/appium/espressoserver/lib/model/settings/DriverSetting.kt
- espresso-server/app/src/androidTest/java/io/appium/espressoserver/lib/model/web/WebAtomDeserializer.kt
- espresso-server/app/src/test/java/io/appium/espressoserver/test/helpers/w3c/PointerDispatchTest.kt
- espresso-server/build.gradle.kts
- package.json
- test/functional/helpers/session.js
Compose driver anyway requires Kotlin 1.5, so we get warnings about two kotlin version being used at the same time during compilation. Also fixed several compiler warnings related to the above version bump.
cc @rajdeepv
> chore: Switch to Kotlin 1.5 and address deprecations

- ci-jobs/pr-validation.yml
- espresso-server/app/src/androidTest/java/io/appium/espressoserver/lib/helpers/SizeHelpers.kt
- test/functional/webview/webatoms-e2e-specs.js
`currentWindowMetrics` has only been added since API 30, so we need to use a proper approach for earlier versions of it
> fix: Update size detection

- espresso-server/app/src/androidTest/java/io/appium/espressoserver/lib/drivers/ComposeDriver.kt
- espresso-server/app/src/androidTest/java/io/appium/espressoserver/lib/model/SourceDocument.kt
- test/functional/commands/jetpack-compose-e2e-specs.js
- test/functional/commands/jetpack-compose-source-e2e-specs.js
When the nodes are merged, the attributes are merged too in an array. For such elements,  during a get_text call, we return only the first text of the array which is wrong. The merging of nodes also kills the possibility to finely locate a merged node's position
This can be solved by using an unmerged tree which gives a more detailed tree better suited for testing purpose
> fix: Use unmerged tree for better details

- espresso-server/app/src/androidTest/java/io/appium/espressoserver/lib/model/ComposeNodeElement.kt
Problem Statement:
- Currently implementation of page source returns element node as "ComposeNode" for most of the elements(except for [Role](https://github.com/androidx/androidx/blob/fc686a1579c3e1d5b1680906835effb4598566b5/compose/ui/ui/src/commonMain/kotlin/androidx/compose/ui/semantics/SemanticsProperties.kt#L544))
- Current [Logic](https://github.com/appium/appium-espresso-driver/blob/master/espresso-server/app/src/androidTest/java/io/appium/espressoserver/lib/model/ComposeNodeElement.kt#L59)
e.g:
```
<ComposeNode bounds="[130,383][234,426]" class="ComposeNode" clickable="false" enabled="true" focused="false" index="0" password="false" properties="" resource-id="2623" scrollable="false" selected="false" text="Games"/>
<ComposeNode bounds="[150,322][213,385]" class="ComposeNode" …
```
> fix: [compose] Fix class names in page source

- espresso-server/app/src/androidTest/java/io/appium/espressoserver/lib/handlers/MobileBackdoor.kt
recent fix #697 had broke this facility to return array types
> fix: allow array return type from backdoor

- lib/driver.js
ADB only does port forwarding for ip4 addresses, so it does not make sense to have `localhost` there if it is pointing to ipv6 address by default.
Addresses https://github.com/appium/appium-espresso-driver/issues/747
> fix: Use ip4 localhost address by default

- lib/driver.js
`.zip` ext local file has not been unzipped since v2.1.0.
To keep compatibility and `this.helpers.configureApp`'s behavior, it would be nice to unzip in `onPostConfigureApp` if the given local file was zipped one.
Then, `onPostConfigureApp` should return a new unzipped file as its response to give the unzipped file to set it as `this.opts.app` for the following process.
> fix: unzip if the file was zipped

- espresso-server/app/build.gradle.kts
- espresso-server/build.gradle.kts
- lib/server-builder.js
Make compose and kotlin versions configurable by users using the `espressoBuildConfig` capability
```
espressoBuildConfig:    '{"toolsVersions": {"composeVersion": "1.1.1", "compileSdk":"31", "kotlin":"1.6.10"}}',
```
> feat: make compose and kotlin dependencies version configurable

- package.json
to fix https://github.com/appium/appium-espresso-driver/issues/770
> chore: bump the base driver version in the published package

- espresso-server/app/src/androidTest/java/io/appium/espressoserver/lib/model/AttributesEnum.kt
**Issue:**
```
io.appium.espressoserver.lib.handlers.exceptions.NotYetImplementedException: Compose doesn't support attribute 'checked', Attribute name should be one of 'bounds', 'class', 'clickable', 'content-desc', 'enabled', 'focused', 'index', 'password', 'resource-id', 'scrollable', 'selected', 'text', 'view-tag'
at io.appium.espressoserver.lib.model.ComposeNodeElement.getAttribute(ComposeNodeElement.kt:126)
```
**Reason:** 
**Checked** attribute not been respected for Compose Driver.
> chore: Support `checked` attribute

- README.md
- espresso-server/app/src/androidTest/java/io/appium/espressoserver/lib/handlers/GetEnabled.kt
- espresso-server/app/src/androidTest/java/io/appium/espressoserver/lib/handlers/GetLocation.kt
- espresso-server/app/src/androidTest/java/io/appium/espressoserver/lib/handlers/GetLocationInView.kt
- espresso-server/app/src/androidTest/java/io/appium/espressoserver/lib/handlers/GetName.kt
- espresso-server/app/src/androidTest/java/io/appium/espressoserver/lib/handlers/GetSelected.kt
- espresso-server/app/src/androidTest/java/io/appium/espressoserver/lib/handlers/GetSize.kt
- espresso-server/app/src/androidTest/java/io/appium/espressoserver/lib/handlers/Text.kt
https://github.com/appium/appium/discussions/17001#discussioncomment-2842792
GetXXXX via elements like displayed has compose handler while some of them had only espresso ones.
This PR adds other GetXXXX for compose.
```
class GetDisplayed : RequestHandler<AppiumParams, Boolean> {
override fun handleEspresso(params: AppiumParams): Boolean =
ViewElement(EspressoElement.getViewById(params.elementId, false)).isVisible
override fun handleCompose(params: AppiumParams): Boolean =
try {
getNodeInteractionById(params.elementId).assertIsDisplayed()
true
} catch (e: AssertionError) {
false
}
}
```
These implementation basically follows existing `class Text : RequestHandler<AppiumParams, String>`'s implementation.
> feat: Add compose support more for element

- README.md
- lib/commands/execute.js
- lib/commands/general.js
Update startActivity to support IntentOptions and passed as optionalIntentArguments. Clients might require update but this should help teams with both UiAutomator2 and Espresso scripts.
> feat: Add `mobile: startActivity` extension

- espresso-server/app/src/androidTest/java/io/appium/espressoserver/lib/helpers/ViewFinder.kt
- espresso-server/app/src/test/java/io/appium/espressoserver/test/model/HamcrestMatcherTest.kt
Hi!
The project uses old version of the hamcrest library v1.3 because it uses internal API http://hamcrest.org/JavaHamcrest/distributables.html#upgrading-from-hamcrest-1x.
I fixed it and added a test to check.
> chore: Update to hamcrest 2.2

- espresso-server/app/src/androidTest/java/io/appium/espressoserver/lib/handlers/Clear.kt
- espresso-server/app/src/androidTest/java/io/appium/espressoserver/lib/handlers/ElementEquals.kt
- espresso-server/app/src/androidTest/java/io/appium/espressoserver/lib/handlers/ElementScreenshot.kt
- espresso-server/app/src/androidTest/java/io/appium/espressoserver/lib/handlers/ElementValue.kt
- espresso-server/app/src/androidTest/java/io/appium/espressoserver/lib/handlers/FindActive.kt
- espresso-server/app/src/androidTest/java/io/appium/espressoserver/lib/handlers/FindElement.kt
- espresso-server/app/src/androidTest/java/io/appium/espressoserver/lib/handlers/FindElements.kt
- espresso-server/app/src/androidTest/java/io/appium/espressoserver/lib/handlers/GetAttribute.kt
- espresso-server/app/src/androidTest/java/io/appium/espressoserver/lib/handlers/GetDisplayed.kt
- espresso-server/app/src/androidTest/java/io/appium/espressoserver/lib/handlers/GetEnabled.kt
- espresso-server/app/src/androidTest/java/io/appium/espressoserver/lib/handlers/GetLocation.kt
- espresso-server/app/src/androidTest/java/io/appium/espressoserver/lib/handlers/GetLocationInView.kt
- espresso-server/app/src/androidTest/java/io/appium/espressoserver/lib/handlers/GetName.kt
- espresso-server/app/src/androidTest/java/io/appium/espressoserver/lib/handlers/GetRect.kt
- espresso-server/app/src/androidTest/java/io/appium/espressoserver/lib/handlers/GetSelected.kt
- espresso-server/app/src/androidTest/java/io/appium/espressoserver/lib/handlers/GetSize.kt
- espresso-server/app/src/androidTest/java/io/appium/espressoserver/lib/handlers/Keys.kt
- espresso-server/app/src/androidTest/java/io/appium/espressoserver/lib/handlers/MobileBackdoor.kt
- espresso-server/app/src/androidTest/java/io/appium/espressoserver/lib/handlers/MobileClickAction.kt
- espresso-server/app/src/androidTest/java/io/appium/espressoserver/lib/handlers/MobileSwipe.kt
- espresso-server/app/src/androidTest/java/io/appium/espressoserver/lib/handlers/MobileViewFlash.kt
- espresso-server/app/src/androidTest/java/io/appium/espressoserver/lib/handlers/PointerEventHandler.kt
- espresso-server/app/src/androidTest/java/io/appium/espressoserver/lib/handlers/WebAtoms.kt
- espresso-server/app/src/androidTest/java/io/appium/espressoserver/lib/helpers/EspressoViewsCache.kt
- espresso-server/app/src/androidTest/java/io/appium/espressoserver/lib/helpers/ViewFinder.kt
- espresso-server/app/src/androidTest/java/io/appium/espressoserver/lib/helpers/w3c/adapter/espresso/EspressoW3CActionAdapter.kt
- espresso-server/app/src/androidTest/java/io/appium/espressoserver/lib/model/Element.kt
- test/unit/driver-specs.js
Addresses https://github.com/appium/appium-espresso-driver/issues/821#issuecomment-1277909305
> fix: Properly fetch view interaction if it was found under a root

- espresso-server/app/src/androidTest/java/io/appium/espressoserver/lib/helpers/ComposeNodeFinder.kt
- espresso-server/app/src/androidTest/java/io/appium/espressoserver/lib/model/SourceDocument.kt
- espresso-server/app/src/androidTest/java/io/appium/espressoserver/lib/viewmatcher/WithXPath.kt
If no matches are found the xpath lookup would be executed for each view matcher in the previous implementation, which is way beyond performant.
> fix: Make sure we only perform xpath lookup once

- README.md
- espresso-server/app/build.gradle.kts
We could set _because_ in the dependency to add the description. They may help our future maintenance. Code comment and this `because` might have no difference to leaving comments on the gradle file, but maybe the error message will change(?). No strong opinion for this option vs code comment though
> chore: add because in the gradle file

- lib/driver.js
- lib/method-map.js
- package.json
depends on https://github.com/appium/appium-android-driver/pull/782
> fix: specify supported non-standard commands in newMethodMap

- README.md
- package.json
- scripts/log-espresso-path.js
- scripts/print-espresso-path.js
similar to opening wda fir, I'd like to show where the espresso server is. This could be on Win as well, so this command shows where it is. This will help when a user wants to modify the gradle file directly in their debug for example. I had questions about where the espresso server was in past, so this command may help in such cases as well.
Example (local installed espresso driver dir)
```
kazu$ appium driver run --json espresso print-espresso-path
{
"output": [
"[STDOUT] /Users/kazu/GitHub/appium-espresso-driver/espresso-server"
]
}
kazu$ appium driver run espresso print-espresso-path
[STDOUT] /Users/kazu/GitHub/appium-espresso-driver/espresso-server
✔ log-espresso-path successfully ran
```
> chore: add print espresso path as a command

- README.md
- espresso-server/app/build.gradle.kts
- lib/server-builder.js
- Recent espresso version bump to [3.5.1](https://github.com/appium/appium-espresso-driver/commit/2193c252cd8f975cd1e9391f594a41d70badd26b#diff-189ca601c158e86b4aeb3c6c244400608b9ed011af10276cdc10884a9a05525aR162) found to be quite flaky for us, especially tests taking twice longer(e.g findElement/s with xpath significantly slower).
- The proposed changes would give possibility to parameterise espresso version.
> feat: add ability to customise espresso dependency version

- espresso-server/app/build.gradle.kts
- espresso-server/app/src/main/AndroidManifest.xml
Fixes: #871
On gradle 8.0 and up, the package name needs to be moved from the manifest file to the build.gradle file
> fix: build app with Gradle 8.x

- espresso-server/app/build.gradle.kts
It seems like `isTransitive = false` caused below error when the compose version was `1.4.3`
```
[debug] [EspressoDriver@633b (599df58e)] [Instrumentation] io.appium.espressoserver.EspressoServerRunnerTest:
[debug] [EspressoDriver@633b (599df58e)] [Instrumentation] Error in startEspressoServer(io.appium.espressoserver.EspressoServerRunnerTest):
[debug] [EspressoDriver@633b (599df58e)] java.lang.AbstractMethodError: abstract method "kotlin.coroutines.CoroutineContext$Key androidx.compose.ui.platform.InfiniteAnimationPolicy.getKey()"
[debug] [EspressoDriver@633b (599df58e)] 	at kotlin.coroutines.CoroutineContext$plus$1.invoke(CoroutineContext.kt:33)
[debug] [EspressoDriver@633b (599df58e)] 	at kotlin.coroutines.CoroutineContext$plus$1.invoke(CoroutineContext.kt:32)
[debug] …
```
> feat: remove isTransitive in compose for newer compose versions

- espresso-server/app/src/androidTest/java/io/appium/espressoserver/lib/handlers/GetAttribute.kt
These lines handle `espressoAttributes` stuff, so the error message also should be `espressoAttributes` instead of composeAttributes
> fix: error message of espresso attribute

- .github/workflows/functional-test.yml
This PR adds API-32 to CI targets.
ref. https://github.com/appium/appium-uiautomator2-driver/pull/614#issuecomment-1572384137
> ci: add api-32 to functional test targets

- espresso-server/app/src/androidTest/java/io/appium/espressoserver/lib/helpers/CustomFailureHandler.kt
- espresso-server/app/src/androidTest/java/io/appium/espressoserver/lib/http/Server.kt
Similar to https://github.com/appium/appium-espresso-driver/pull/894, but should also work for earlier Espresso versions
> feat: Disable screenshots and hierarchy snapshots on failures

- README.md
As https://github.com/appium/appium-espresso-driver/pull/879 , I met a case the compose dependencies prevented working the appium espresso driver well. Some cases were compile error, the other cases were launching the instrument process.
So, I'd like to keep https://github.com/appium/appium-espresso-driver/pull/879 branch (no-compose-deps) to reduce struggling with coordinating the build dependencies experience.
I'd also like to address the branch in the README to help such users.
> docs: address no compose deps branch

- lib/commands/general.js
As same as UIA2, maybe should this driver also call `this.settings` stuff to call plugins?
Fixes https://github.com/appium/appium-espresso-driver/issues/900
> fix: calls this.settings in settings handling

- lib/commands/general.js
As same as other drivers, espresso driver also does not return an error to the client. Instead, the error response by the espresso server will be the appium log.
example:
```
[HTTP] --> POST /session/37f7067e-2470-4984-a4bc-237f8dc60b6b/appium/settings
[HTTP] {"settings":{"animationCoolOffTimeout":0,"waitForIdleTimeout":1}}
[debug] [EspressoDriver@e161 (37f7067e)] Calling AppiumDriver.updateSettings() with args: [{"animationCoolOffTimeout":0,"waitForIdleTimeout":1},"37f7067e-2470-4984-a4bc-237f8dc60b6b"]
[debug] [EspressoDriver@e161 (37f7067e)] Matched '/appium/settings' to command name 'updateSettings'
[debug] [EspressoDriver@e161 (37f7067e)] Proxying [POST /appium/settings] to [POST http://127.0.0.1:8300/session/15112ec3-ba21-48f1-927d-761a0df577a0/appium/settings] with body: …
```
> fix: do not reply error message in updateSettings to follow other drivers

- package.json
Reverts appium/appium-espresso-driver#904
https://github.com/appium/appium-espresso-driver/issues/905
saw the same one in the ruby_lib_core tests as well. I’ll take a look later further what happened
> chore(deps-dev): revert “bump semantic-release from 20.1.3 to 21.1.0"

- espresso-server/app/build.gradle.kts
Fixes issue when passing `-PappiumKeystoreFile=/storeFile -PappiumKeystorePassword=passwd1 ... ` did not result in properly signed binary. It was always signed by `AndroidDebugKey`
Root cause of the issue - incorrect use of `apply` API in place, and creating File instance for passwords and alias.
How to verify:
```shell
./gradlew \
signingReport
```
vs:
```shell
./gradlew \
-PappiumZipAlign=true \
-PappiumKeystoreFile="${PWD}/my_ci.keystore" \
-PappiumKeystorePassword=my_ci_store_password \
-PappiumKeyAlias=my_alias \
-PappiumKeyPassword=my_ci_key_password \
-PappiumTargetPackage=my.package \
signingReport
```
> fix: signingConfigs for test apk

- package.json
Reverts appium/appium-espresso-driver#916
The same issue reported after https://github.com/appium/appium-espresso-driver/pull/909 occurred in https://github.com/appium/appium-espresso-driver/issues/931
```
kazu@laptop espresso-server % ls
app                 build.gradle.kts    gradle.properties   gradlew             gradlew.bat         lint.xml            settings.gradle.kts
kazu@laptop espresso-server % ./gradlew
Error: Could not find or load main class org.gradle.wrapper.GradleWrapperMain
Caused by: java.lang.ClassNotFoundException: org.gradle.wrapper.GradleWrapperMain
```
I haven't dug into the root cause, but it seems like gradlew is broken right now
> Revert "chore(deps-dev): bump semantic-release from 20.1.3 to 22.0.5"

- espresso-server/app/src/androidTest/java/io/appium/espressoserver/lib/handlers/WebAtoms.kt
Fixes: https://github.com/appium/appium-espresso-driver/issues/937
I'm not too happy with the return value.
```kotlin
return if (params.methodChain.size == 1) "success" else webViewInteraction.get().toString()
```
However, the request handler is handling all webAtom methods available in https://developer.android.com/reference/androidx/test/espresso/web/webdriver/DriverAtoms#public-methods. So not sure how to handle the different return types of all methods available.
> feat: Return web atom response

- README.md
- lib/commands/general.js
- package.json
Selenium binding implicitly mutates `element` argument values and we don't want this to happen, so I renamed it to `elementId`, like it was already done in UIA2.
Also dropped the single validate.js import used for a single method args validation and implemented the validation myself
> chore: Update arguments validation in several mobile extensions

- README.md
- lib/commands/execute.js
- package.json
Based on https://github.com/appium/appium-android-driver/pull/884
> feat: Add support of UiModeManager service commands

- lib/commands/general.js
- lib/driver.js
- package.json
Similar to https://github.com/appium/appium-android-driver/pull/897
> feat: Use APIs imported from the io.appium.settings package

- lib/commands/app-management.js
- lib/driver.ts
Figured out the "overload" fixed https://github.com/appium/appium-espresso-driver/pull/975
https://austingil.com/typescript-function-overloads-with-jsdoc/
So, if CI passes (simple npm install as well), this will be ok
> fix: add overload to fix type issue

- lib/commands/screenshot.js
- lib/driver.ts
Fixes https://github.com/appium/appium-inspector/issues/1273
With `nativeWebScreenshot`, we want to proxy requests to the espresso server instead of the chromedriver. To handle it, we should add getScreenshot explicitly to prevent not implemented error.
https://github.com/appium/appium-espresso-driver/blob/619d177700084c3916b569397bac922d00d0cf19/lib/driver.ts#L686-L689
It looks like the removal of `getScreenshot` occurred in the appium-android-driver major version update as https://github.com/appium/appium-inspector/issues/1273#issuecomment-1928972593, but the implementation also raised `throw new errors.NotImplementedError('Not implemented');` so I guess somewhere overridend before.
Tested with `"appium:nativeWebScreenshot": true` and without it.
e.g.
```
[HTTP] --> GET …
```
> fix: proxy request to the espresso server with nativeWebScreenshot

- lib/server-builder.js
Addresses https://github.com/appium/appium-espresso-driver/issues/996
> fix: Set `shell` option to true while running gradle script on Windows

- lib/commands/execute.js
- lib/driver.ts
- package.json
Similar to https://github.com/appium/appium-uiautomator2-driver/pull/780
> feat: Align execute methods implementation with other android drivers

- README.md
- lib/driver.ts
- lib/espresso-runner.js
- package.json
https://github.com/appium/appium-adb/pull/745 method instead of `--no-window-animation` for espresso since the flag in espresso instrumentation process did not bring the animation scale back after the process kill.
0/1 for animation scale is to make the behavior as same as `this.settingsApp.setAnimationState`
> chore: set animation scale via settings for api level 26+

- package.json
To use api level 32 built settings apk
> chore: use latest io.appium.settings

- lib/driver.ts
to fix:
```
lib/driver.ts:689:3 - error TS2742: The inferred type of 'getProxyAvoidList' cannot be named without a reference to 'appium-android-driver/node_modules/@appium/types'. This is likely not portable. A type annotation is necessary.
689   getProxyAvoidList (sessionId) {
~~~~~~~~~~~~~~~~~
```
> fix: type error in the build

- package.json
as same as https://github.com/appium/appium-uiautomator2-driver/pull/794
> fix: Add a workaround for wrong adb exit code on service stop

- espresso-server/app/build.gradle.kts
- espresso-server/build.gradle.kts
- espresso-server/gradle/wrapper/gradle-wrapper.properties
I'll bump the android gradle plugin version to 8.5.0 and targetSdk version to 34 (current latest) later but let's bump the android gradle wrapper version first to v8 from v7 (major version update) as a separate version
> feat: bump default gradle wrapper to 8.7.0 and android plugin to 8.0.0

- espresso-server/library/build.gradle.kts
- jitpack.yml
This is the minimum required configuration to make the library accessible via JitPack.
JitPack sets groupId, artifactId and version automatically. The Maven coordinates of the library will be `com.github.appium:appium-espresso-driver:<tag>`.
> feat: Publish Espresso server library to JitPack

- espresso-server/library/src/main/java/io/appium/espressoserver/lib/handlers/Status.kt
- espresso-server/library/src/main/java/io/appium/espressoserver/lib/helpers/Version.kt
- espresso-server/library/src/main/java/io/appium/espressoserver/lib/http/Router.kt
- espresso-server/library/src/main/java/io/appium/espressoserver/lib/model/AppiumParams.kt
- espresso-server/library/src/main/java/io/appium/espressoserver/lib/model/Location.kt
- espresso-server/library/src/main/java/io/appium/espressoserver/lib/model/Rect.kt
- espresso-server/library/src/main/java/io/appium/espressoserver/lib/model/Size.kt
- espresso-server/library/src/main/java/io/appium/espressoserver/lib/model/Status.kt
- espresso-server/library/src/main/java/io/appium/espressoserver/lib/model/WindowRect.kt
- espresso-server/library/src/main/java/io/appium/espressoserver/lib/model/WindowSize.kt
- package.json
- scripts/sync-version.js
Now, when the server part could be integrated into the application under test separately, it is important that the driver knows the server version to check it for possible compatibility issues.
Also, the response format itself has been updated to comply with [W3C requirements](https://www.w3.org/TR/webdriver2/#dfn-status)
> feat: Add proper info to the /status API response

- espresso-server/library/src/main/java/io/appium/espressoserver/lib/model/SourceDocument.kt
We can have modifications in the nodes when traversing through them in `serializeComposeNode`, so it's important to cache children before printing them. Similar approach is [used](https://cs.android.com/androidx/platform/frameworks/support/+/androidx-main:compose/ui/ui-test/src/commonMain/kotlin/androidx/compose/ui/test/Output.kt;l=206?q=compose%2Fui%2Ftest%2FOutput.kt) in compose-ui-test when printing compose nodes.
<details>
<summary>This is to prevent stack traces like that one</summary>
```Responding to server with error: {error=unknown error, message=java.lang.IndexOutOfBoundsException: Index 5 out of bounds for length 5, stacktrace=java.lang.IndexOutOfBoundsException: Index 5 out of bounds for length 5
at jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:64)
at …
```
> fix: Cache children in serializeComposeNode

- .github/workflows/functional-test.yml
- docs/hybrid-mode.md
- package.json
This bump disables automatic chromedriver download upon module installation
> feat: Bump android driver

- README.md
- package.json
As same as https://github.com/appium/appium-uiautomator2-driver/pull/867 . I'll merge after CI pass
> feat: add more params in mobile: setGeolocation

- lib/driver.ts
- lib/execute-method-map.ts
The main typo fix is set's one. The type caused:
```
[HTTP] --> POST /session/be6b7c51-e619-4631-9e2e-0eb116629592/execute/sync
[HTTP] {"script":"mobile:setClipboard","args":[{"contentType":"plaintext","content":"aGFwcHkgdGVzdGluZw==","label":"Note"}]}
[EspressoDriver@9cd6 (be6b7c51)] Calling AppiumDriver.execute() with args: ["mobile:setClipboard",[{"contentType":"plaintext","content":"aGFwcHkgdGVzdGluZw==","label":"Note"}],"be6b7c51-e619-4631-9e2e-0eb116629592"]
[EspressoDriver@9cd6 (be6b7c51)] Encountered internal error running command: TypeError: Cannot read properties of undefined (reading 'call')
[EspressoDriver@9cd6 (be6b7c51)]     at EspressoDriver.executeMethod (/Users/kazu/.nvm/versions/node/v18.20.2/lib/node_modules/appium/node_modules/@appium/base-driver/lib/basedriver/commands …
```
> fix: fix typo in mobile clipboard commands

- lib/commands/actions.js
- test/functional/commands/contexts-e2e-specs.js
- test/functional/commands/element-values-e2e-specs.js
- test/functional/commands/keyboard-e2e-specs.js
- test/functional/commands/mobile-e2e-specs.js
use an object spread instead of Object.assign to make it more concise and readable
> refactor: use an object spread instead of Object.assign

- .github/workflows/functional-test.yml
- espresso-server/library/src/main/java/io/appium/espressoserver/lib/handlers/WebAtoms.kt
- espresso-server/library/src/main/java/io/appium/espressoserver/lib/model/web/WebAtomsParams.kt
- espresso-server/library/src/test/java/io/appium/espressoserver/test/model/web/WebAtomsTest.kt
- test/functional/webview/webatoms-e2e-specs.js
The original issue was the README addressed `webviewEl` while our actual implementation referred to `webviewElement`. So after correcting it in https://github.com/appium/appium-espresso-driver/pull/1042 to follow README, it started failing.
https://github.com/appium/appium-espresso-driver/issues/1074
This is a fix to follow the `webviewEl` by following `lib/execute-method-map.ts` and README documentation.
I also had the same error in https://github.com/appium/ruby_lib_core/actions/runs/16225328137/job/45864088476
```
I0713 01:36:25.645430    5442 VkDecoderGlobalState.cpp:9181] Destroyed VkInstance:0x55b99ec3f800 for application: engine:.
ERROR AppiumLibCoreTest::Android::MobileCommandsTest#test_webatom (303.94s)
Minitest::UnexpectedError: …
```
> fix: naming of webviewEl in mobile: webAtoms

- .github/workflows/functional-test.yml
- ci/run-functional-tests.sh
- espresso-server/library/src/main/java/io/appium/espressoserver/lib/handlers/MobileSwipe.kt
- lib/commands/element.js
- test/functional/commands/mobile-e2e-specs.js
As part of https://github.com/appium/appium/issues/21426 work, I found out two regressions.
1. do not run on the main thread error
- espresso-server/library/src/main/java/io/appium/espressoserver/lib/handlers/MobileSwipe.kt
2. `"scrollTo" must be one of...` was raised while it didn't provide `scrollTo`
Tests on CI is bad as slow performance on CI...
On my local for `mobile-e2e-specs.js`:
```
2025-09-02T04:19:36.045Z INFO webdriver: COMMAND deleteSession()
2025-09-02T04:19:36.046Z INFO webdriver: [DELETE] http://127.0.0.1:4567/session/9802dd20-2b30-4e20-a4e8-04a5c51c61ef
2025-09-02T04:19:36.561Z INFO webdriver: RESULT null
26 passing (2m)
1 pending
```
> fix: fix regression of scroll guesture in mobile

- lib/driver.ts
To fix:
```
lib/driver.ts:156:14 - error TS2420: Class 'EspressoDriver' incorrectly implements interface 'ExternalDriver<{ readonly platformName: { readonly isString: true; readonly inclusionCaseInsensitive: readonly ["Android"]; readonly presence: true; }; readonly deviceName: { readonly isString: true; }; readonly appActivity: { ...; }; ... 95 more ...; readonly appLocale: { ...; }; }, ... 5 more ..., StringRecord>'.
The types returned by 'getAppiumSessionCapabilities()' are incompatible between these types.
Type 'Promise<SessionCapabilities<{ readonly platformName: { readonly isString: true; readonly inclusionCaseInsensitive: readonly ["Android"]; readonly presence: true; }; readonly deviceName: { readonly isString: true; }; ... 85 more ...; readonly injectedImageProperties: { ...; }; …
```
> fix: typecheck
